### ISSUE TITLE
esteemapp account shouldn't require active/master key to schedule post

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#101]
Seems all other accounts needs that, but whenever we post from @esteemapp it needs only posting key actually.

<img width="420" alt="2018-07-02 22 56 43" src="https://user-images.githubusercontent.com/32987666/42183711-8f97348c-7e4b-11e8-850a-e798f66e6633.png">

**Comment by talhasch** [comment]
In order to create new post behalf of user, we need to update user data.

**Comment by feruzm** [comment]
@talhasch yes we add `esteemapp` to user's posting permission but for `esteemapp` account itself doesn't need that, this is only for that exception

**Comment by talhasch** [comment]
@feruzm hmm ok. will add code to fix it
