### ISSUE TITLE
Login button looks like Exit

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#102]
One user asked me how to login to Surfer. He thought that login button in the header top right corner is exit from the app. Maybe we should change that to empty avatar (or avatar with ? or ! sign)? How do you think, guys?

**Comment by feruzm** [comment]
Yeah it is quite small and confusing icon. We should use word with button perhaps or have tooltip saying login and logout when mouse hover...

**Comment by talhasch** [comment]
Tooltips added to all buttons on right of top navbar.
![image](https://user-images.githubusercontent.com/1177676/42744630-a671ecb6-88d6-11e8-91b7-3aa4125ec50d.png)
