### ISSUE TITLE
Voting percentage issue: could not vote

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#103]
Trying to vote with small percentage getting this error:

<img width="1440" alt="2018-07-03 12 54 10" src="https://user-images.githubusercontent.com/32987666/42213004-56b2030c-7ec0-11e8-846e-99ad3f3763be.png">

**Comment by fildunsky** [comment]
`Error: transaction.operations = vote,[object Object]	cause: vote.weight = 819.9999999999999 cause: Illegal value: 819.9999999999999 (not an integer) stack: TypeError: Illegal value: 819.9999999999999 (not an integer) at ByteBuffer.module.exports.ByteBufferPrototype.writeInt16 (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bytebuffer/dist/bytebuffer-node.js:677:23) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:182:11) at Serializer.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:71:26) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:846:26) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:397:30) at Serializer.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:71:26) at Serializer.toByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:198:18) at Serializer.toBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:204:36) at Object.Auth.signTransaction (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/index.js:116:24) at /Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/broadcast/index.js:52:64 at tryCatcher (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:638:18) stack: Error: vote.weight = 819.9999999999999 cause: Illegal value: 819.9999999999999 (not an integer) stack: TypeError: Illegal value: 819.9999999999999 (not an integer) at ByteBuffer.module.exports.ByteBufferPrototype.writeInt16 (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bytebuffer/dist/bytebuffer-node.js:677:23) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:182:11) at Serializer.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:71:26) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:846:26) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:397:30) at Serializer.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:71:26) at Serializer.toByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:198:18) at Serializer.toBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:204:36) at Object.Auth.signTransaction (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/index.js:116:24) at /Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/broadcast/index.js:52:64 at tryCatcher (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:638:18) at Function._throw (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/error_with_cause.js:35:19) at Serializer.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:78:29) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:846:26) at Object.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/types.js:397:30) at Serializer.appendByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:71:26) at Serializer.toByteBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:198:18) at Serializer.toBuffer (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/serializer/src/serializer.js:204:36) at Object.Auth.signTransaction (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/auth/index.js:116:24) at /Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/steem/lib/broadcast/index.js:52:64 at tryCatcher (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:638:18) at Promise._resolveCallback (/Applications/eSteem Surfer.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:432:57)`

**Comment by feruzm** [comment]
this is due to Steem does rounding on integers and in app we are allowing decimals in percent that's why sometimes this error shows up from blockchain. solution would be to not allow decimals `1.23%` but I think it is more valuable to have decimals, only thing here if @talhasch can catch this error, can show more meaningful error message.

**Comment by talhasch** [comment]
actually it is weird and i have no idea how it happened because voting slider's increment step is 0.1 and it should not generate floating number when multiplied by 100 (maybe slider's bug)

i think it is better to use parseInt on vote weight to make sure it is integer.

what you say @feruzm

**Comment by feruzm** [comment]
yes, let's do this to avoid weird UX.
