### ISSUE TITLE
Enchancement: better use of space

### ISSUE THREAD

**Issue by AndaBlackWidow** [esteemapp/esteem-surfer#106]
Current layout of Surfer resembles that of steemit. Steemit might be excused because such layout suits better when viewed on smartphone, but in case of desktop app like Surfer it has no justification. There is simply too much empty space on both sides of actual text.

My proposition is to add new mode (either version or both separately):
1. split window in half and show main post on the left with comments on the right
2. keep main post on top of comments like today but fit all texts to whole window

Version 1 is conservative - there will still be plenty of empty space, just not as much as today, but a plus is that there won't be any risk of weird rearrangement of post/comment content.

**Comment by talhasch** [comment]
thanks for your feedback and interest but your recommendations don't fit to our visual design style.
