### ISSUE TITLE
Voting power in footer

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#107]
@thecrytotrader wrotes: "is it possible to make a notification type alert that show us our remaining Upvoting power after each upvote because sometimes we do over Upvoting without seeing our voting power so it would be great if esteem automatically tell us how much voting power left  after each upvote that we give to ourselves and others."

I also found myself voting too much draining my VP.

Can we move current voting power to the footer where the version number, about and faq located?

**Comment by talhasch** [comment]
sounds like great feature. what do you think @feruzm ?

**Comment by fildunsky** [comment]
We can move FAQ and About to native OS menu by the way e.g.
Help -> About
Help -> FAQ

**Comment by feruzm** [comment]
I like idea of moving some crucial information on footer, but don't want to crowd screen as well. should be delicate about these details, maybe have battery icon and tooltip to give extra info?! About notification part, I think once we have notification, we can notify user that they did 10 or 20, 30, 40 votes last 24 hours, this would be useful information.

**Comment by feruzm** [comment]
>We can move FAQ and About to native OS menu by the way e.g.
Help -> About
Help -> FAQ

I think @fildunsky, we want to keep as many things within UI as possible, moving to Electron part makes it difficult to convert to web app when we come to that. Unless @talhasch thinks it is easy to move them around.

**Comment by fildunsky** [comment]
For the menus it makes sense, I got it!

Notifications could look like this, what do you think?

![vp](https://user-images.githubusercontent.com/32987666/42384772-8f5e8678-8143-11e8-8c04-bdd44903799a.png)

![vp2](https://user-images.githubusercontent.com/32987666/42386451-3ac65c08-8148-11e8-949f-b4141deca58e.png)

**Comment by feruzm** [comment]
I like style of notification, about place/location of it, not sure... It should be top right corner below navigation header perhaps, user naturally want to look there to see notification?!

**Comment by talhasch** [comment]
i like first one. top section of app is pretty crowded. i think the best place to add it is footer bar like first one @feruzm

**Comment by fildunsky** [comment]
![vp_top](https://user-images.githubusercontent.com/32987666/42390482-b43bb9fa-8154-11e8-9cce-34ee1307bf03.png)
Oh yes, top right corner could much more intuitive for users to close notifications. I've just read an article on https://goodui.org/ about that yesterday but forgot to try it out :)

**Comment by fildunsky** [comment]
### Rounded corners

It's same rounds as for the search field in the header menu.

![vp2](https://user-images.githubusercontent.com/32987666/42396171-4f931f10-8169-11e8-87bb-d544286d0404.png)

**Comment by talhasch** [comment]
Added voting power on footer without notification. For now it highlights voting power area when voting power changed like below. 
![image](https://user-images.githubusercontent.com/1177676/42821011-38779f02-89e0-11e8-80db-a97c3dbf38fa.png)

**Comment by talhasch** [comment]
Btw voting power notification will be added soon...

**Comment by fildunsky** [comment]
Looks cool!

**Comment by talhasch** [comment]
Lets track footer improvements under #172 Closing this one.
