### ISSUE TITLE
Unread/read posts

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#109]
We was discussing with @feruzm that grey out header and text of posts previews (visited posts links) when it's already read by users lack something and found out simple way to improve it. Let's keep text color for header and post text black but add this small dot (option). Empty circle means unread. Circle with dot inside could mean read.

It's not obvious but for those who care will make sense later and we could create educational post on that. This dot is in between post #tag and post timing area.

What do you say?

### Grey variant

![unread1](https://user-images.githubusercontent.com/32987666/42393947-01a95f74-8161-11e8-82fc-88acbd63d359.png)

![unread1b](https://user-images.githubusercontent.com/32987666/42393946-0164a500-8161-11e8-8244-c60afa9efa46.png)

### Blue variant

![unread2](https://user-images.githubusercontent.com/32987666/42393963-0f0a56d2-8161-11e8-9a37-0a343a852b76.png)

![unread2b](https://user-images.githubusercontent.com/32987666/42393961-0ed91c48-8161-11e8-91e1-6bceb0632bb1.png)

**Comment by talhasch** [comment]
I can say better than current one. but i am not sure if it's noticeable enough by user. what do you say @feruzm

**Comment by fildunsky** [comment]
12 px was too small, edited to 16 px. I don't know if it could be done with CSS but can add .PNGs in case they needed

**Comment by talhasch** [comment]
![image](https://user-images.githubusercontent.com/1177676/42600937-b5628aa4-856c-11e8-95b4-dfaa59db54db.png)

what do you say @fildunsky ?

**Comment by fildunsky** [comment]
Looking good!

**Comment by fildunsky** [comment]
![eye](https://user-images.githubusercontent.com/32987666/42747707-2a06d58c-88e6-11e8-8a98-8a10f11a6a44.png)

Hey guys, I've found this small dot is confusing even myself :) I don't understand what is read and what is unread that way. How do you think maybe we could change this into eye icon? Suppose active color (blue) eye striked through eye means you haven't read it yet. Passive (gray) open eye means you already read it. Check the screen above for example please.

**Comment by feruzm** [comment]
Maybe we should just swap `o` for already read and `•` not read? I think it would be more meaningful... eye would be even more confusing because it might say it is `nsfw` or something that shouldn't be watched :)

**Comment by fildunsky** [comment]
Yes, it may work, let's try and see...

**Comment by talhasch** [comment]
swapped icons. pls check it @fildunsky @feruzm

**Comment by feruzm** [comment]
lgtm
