### ISSUE TITLE
Navigation interface rework

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#110]
### Houston, we have a problem...

We have same links living in different places of the app...

![problem](https://user-images.githubusercontent.com/32987666/42391366-ccc0fb4a-8157-11e8-92f2-80ef5208829d.png)

### Sketch 01

This is my first try. Please comment on that. Any thoughts appreciated. What do you think about icons? Are they adding more visual noise or helping user to find menus faster?

![menu](https://user-images.githubusercontent.com/32987666/42395836-f3122048-8167-11e8-9560-c847d355891a.png)

**Comment by fildunsky** [comment]
Menu with icons probably needs more space in between lines... I'll check if you like.

**Comment by talhasch** [comment]
i am closing this issue @fildunsky something more great is coming :)
