### ISSUE TITLE
Reading mode changes window size

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#114]
Whenever I switch to reading mode Surfer window shrinks even if window is maximized. Switching back to normal mode also shrinks the window. I want it to stay full screen but seems Surfer does not respect system settings.

I've checked on Windows and Mac.

**Comment by talhasch** [comment]
changed the way it works. when you enable reading mode it makes window full screen then when you disable reading mode window size does not changed. I think this way more useful.
