### ISSUE TITLE
0 reputation users are shown in search

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#116]
Would be great to mute users with small reputation (0 or minus) from search results list similar to steemit.com

![0](https://user-images.githubusercontent.com/32987666/42472344-9df641f2-83c9-11e8-8f30-5d4ff553a751.png)

**Comment by feruzm** [comment]
In future we will have customizable search with various filters, there is some work being made behind the scenes 😊 Until our Search engine is fully ready, let's keep this as is. Because content search is still relevant regardless of the reputation.
