### ISSUE TITLE
Image bulk upload issue

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#117]
When uploading more than one image at a time first image is sticking to the cursor position in post editor which is good and expected but all the others are adding in the very bottom of the post without line change using only one space in between them.

### What would be handy:
1. Respect cursor position for all the images in bulk upload
2. Every next image link could have two enters or two next line spaces similar to `<br><br>` code so they will not stick to each other.

**Comment by talhasch** [comment]
@fildunsky i think we solved this issues with version 2 what do you think?

**Comment by fildunsky** [comment]
Yes, now it works perfect. Let's close this issue.
