### ISSUE TITLE
Comment field open by default [discussion]

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#120]
Let's discuss to see if it encourages more comments if we leave comment field open by default...

![image](https://user-images.githubusercontent.com/3015990/42674691-73f7e0d8-8679-11e8-82e3-08cf754a6007.png)

What do you guys think? @talhasch @fildunsky

**Comment by talhasch** [comment]
better to encourage users to commenting   👍

**Comment by fildunsky** [comment]
Yes, good option!

**Comment by feruzm** [comment]
great then it is decided, we will try this feature. thanks for feedback!

**Comment by talhasch** [comment]
implemented with last release. closing.
