### ISSUE TITLE
Top posts feature [discussion]

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#121]
Let's use our eSync for this feature as well. When you open any account, get user's top 3 posts if user has more than 10 posts.

Post that is considered top has following criteria:

* Most comments
* Most voted
* Most reblogged
* Most earned - tricky, so above 3 should be sufficient.

Style of `Top Posts` could be similar like `Similar posts` feature we have. 

![image](https://user-images.githubusercontent.com/3015990/42721324-a23af034-8741-11e8-8c82-87ccb999dbe1.png)

**PS.** Feature should be fault tolerant, if backend or eSync is down, it shouldn't show anything and app should continue to work as usual (same goes to any external integrations with our servers [drafts, schedules, etc.]) Because we want Surfer continue to function even if one server fails to return data.

Any suggestions, feedback or improvement on design would be great... @fildunsky, @talhasch

**Comment by talhasch** [comment]
👍also maybe we can allow users to modify this list in future.

**Comment by feruzm** [comment]
interesting, you mean like pinning post, right... I like that, maybe we should call it pinning post and allow user to feature themselves? Pin maximum 3 posts or something like that?!

**Comment by fildunsky** [comment]
I love this feature. We could pin top posts by default and if user wants he could replace that posts by his choice.

Also love the placement of it. Everything is great. Plus maybe we should have checkbox in settings to disable this feature if someone don't want it...

**Comment by talhasch** [comment]
i agree @fildunsky by default it shows 3 top posts. and user can change this list. much better.

**Comment by feruzm** [comment]
great, another question is: do we allow to change it to their own posts only or can pin any other author's post as well?

**Comment by fildunsky** [comment]
I think it should be related to current user posts only (well, maybe resteemed posts as well).
