### ISSUE TITLE
Double entries in activities

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#122]
Possible bug...

![image](https://user-images.githubusercontent.com/3015990/42722043-d18f9b08-874d-11e8-9bee-10a477923d3b.png)

**Comment by talhasch** [comment]
not an actual bug. sent multiple notifications because she updated same post with all content for 4 times. will add a check to enotify-py to prevent this.

**Comment by feruzm** [comment]
yeap makes sense, I had that as well before in mobile notifications... it is tricky though, if someone mentions user after their edit then that notification might not come through if new filter drops out edits.
