### ISSUE TITLE
Activities open filters out link/button

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#125]
Instead of dropdown to filter, have filters text out like in image list of words, allow quick filtering... of course in smaller fonts, image is just to give an idea... @fildunsky might give some mockups

![image](https://user-images.githubusercontent.com/3015990/42780116-16b6777a-894b-11e8-958a-d30a72c44906.png)

**Comment by fildunsky** [comment]
Looking better! I can mock up tomorrow. I think current tab should be active like blue button and others just gray texts without button outline.

If you need a mock up, I will do tomorrow.

**Comment by talhasch** [comment]
looking great. @fildunsky it would be very useful if you can make a mockup.

**Comment by fildunsky** [comment]
@talhasch Your variant looks good, I like it.
I was thinking on this:

- To remove button outlines and make texts look less active
- Maybe change mark all read to icon

But I need your feedback on this, guys @feruzm & @esteemapp/core

**Comment by fildunsky** [comment]
![act2](https://user-images.githubusercontent.com/32987666/42826801-f9ca0c3c-89ed-11e8-880b-01075b5ed022.png)

**Comment by feruzm** [comment]
I like above screen, button should have tooltip as usual otherwise, looking good 👍 thanks @fildunsky 
@talhasch let's also consider adding Transfer and Account updates activities maybe later if it requires involved changes on backend

**Comment by talhasch** [comment]
@fildunsky adapted above but font awesome has no double check icon i had to use single check.

@feruzm i am starting to work on backend to add transfer and account updates.

**Comment by feruzm** [comment]
lgtm
backend: ok

**Comment by fildunsky** [comment]
Great improvement! Much easier to switch using these new tabs now!

**Comment by fildunsky** [comment]
![act3](https://user-images.githubusercontent.com/32987666/42842767-cc103b08-8a16-11e8-9b09-fb019aaadb82.png)
This is not related to activities but now we can remove outline from these buttons as well...

**Comment by fildunsky** [comment]
P.S. Why post titles are not bold by the way?

**Comment by feruzm** [comment]
@fildunsky they look bold to me
@talhasch let's try some border removing and prepare release today.

following changes in addition to what Fil suggested in last screen:
This button can have no background of blue, just plain button/icon like others... bookmarked button can have blue color though
1. ![image](https://user-images.githubusercontent.com/3015990/42856587-8980b096-8a4e-11e8-87b1-75e4847bac4d.png)

border removal
2. ![image](https://user-images.githubusercontent.com/3015990/42856676-e86c808a-8a4e-11e8-82a7-9613accce077.png)
3. ![image](https://user-images.githubusercontent.com/3015990/42856836-9fd2796e-8a4f-11e8-94cc-89a706a4d0d8.png)
4. ![image](https://user-images.githubusercontent.com/3015990/42856820-8d5a27f0-8a4f-11e8-8fab-a2a6ee0f8438.png)

Last one requires preview before committing for the change

**Comment by fildunsky** [comment]
@talha do you mean they look bold in Mac OS? Or in my screenshot here? I'm on Windows now, can not check Mac in nearest 3 days.

**Comment by talhasch** [comment]
borders removed globally for buttons on post list headers

![image](https://user-images.githubusercontent.com/1177676/42870343-4b0821c8-8a80-11e8-9e80-e76b39d15416.png)

![image](https://user-images.githubusercontent.com/1177676/42870365-58912f06-8a80-11e8-92ed-9d1c548f49f9.png)

![image](https://user-images.githubusercontent.com/1177676/42870382-64828076-8a80-11e8-9e74-e7668b8c4dc6.png)

![image](https://user-images.githubusercontent.com/1177676/42870398-6e398902-8a80-11e8-8b2a-d147f92e76b6.png)

![image](https://user-images.githubusercontent.com/1177676/42870433-8587fb3e-8a80-11e8-9d6b-1184c6878ff1.png)

bookmark button also updated 

not bookmarked:
![image](https://user-images.githubusercontent.com/1177676/42870471-a5cf17f6-8a80-11e8-81e8-afd8c5d9a4ab.png)

bookmarked:
![image](https://user-images.githubusercontent.com/1177676/42870506-b9bbde16-8a80-11e8-80c0-41270a21bbed.png)

borders removed from post side menu buttons

![image](https://user-images.githubusercontent.com/1177676/42870569-df046080-8a80-11e8-958c-983cbbf8d2eb.png)

**Comment by feruzm** [comment]
looking great 😍

**Comment by feruzm** [comment]
tags search button remains with border, @talhasch

**Comment by talhasch** [comment]
@fildunsky windows renders `font-weight: 500` as not bold. (hate windows) when i increased it to 600 it looks like too much bold.  check below.

![image](https://user-images.githubusercontent.com/1177676/42871644-8755b8f4-8a83-11e8-974a-8a5b9883bdfe.png)

**Comment by talhasch** [comment]
@feruzm updated

**Comment by feruzm** [comment]
maybe do 600 if platform is windows?!

**Comment by talhasch** [comment]
as principle i don't like to make os based improvements but i think we have to do it. :(

**Comment by fildunsky** [comment]
![bold_header_windows10](https://user-images.githubusercontent.com/32987666/42876423-499b5a94-8a8f-11e8-9eb2-cfb1f2102896.png)
@talhasch in your screen it looks fine but I've updated and see no changes at my side now

**Comment by fildunsky** [comment]
Cool! Finally Windows/Linux renders bold as bold!
