### ISSUE TITLE
Editor UI improvements

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#128]
Small suggestions:
- Move `Save` button closer to `Post` button
- Remove outline from `Save` button to change visual priority for user. Main action is to post now...
- We could rename `Save` to `Save Draft`
- `Clear` button may be even less active visually. May we change it to `Clear All`? How do you think?
- Add confirmation after pressing `Clear` button (Something like: This will clear all the text fields in your current window and you will have to start again. Are you sure?). Since someone could accidentally delete all the texts from the editor window by mistake.

![editor](https://user-images.githubusercontent.com/32987666/42867069-1f2f33ce-8a77-11e8-812d-0f7f52c95167.png)

**Comment by feruzm** [comment]
I agree with all points, moving to highest priority to work on next... perhaps rewards could also be expanded like Activities we did?

**Comment by fildunsky** [comment]
Hmm... not sure... seems too many buttons and options in a row at the same time. For me it's distracting. What do you say?

![editor2](https://user-images.githubusercontent.com/32987666/42868832-03050b10-8a7c-11e8-91b1-1c579d987e65.png)

**Comment by feruzm** [comment]
yeah, for now we can keep it as is then inside select options.

**Comment by fildunsky** [comment]
Lets swap these two buttons as well and remove outline from `Cancel` button

![comments_swap](https://user-images.githubusercontent.com/32987666/42895913-f34b11b8-8ac3-11e8-9243-50a052828c84.png)

**Comment by talhasch** [comment]
new look

![image](https://user-images.githubusercontent.com/1177676/43513920-ad9cf8e2-9587-11e8-9913-1e9f170ef1ff.png)

**Comment by fildunsky** [comment]
Looking great!
