### ISSUE TITLE
Search current page (Ctrl+F)

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#129]
Sometimes I am forgetting this is not a browser and trying to search some text in current page with `Ctrl+F` hotkey. Is it possible to quickly add this as a hotkey or in rightclick menu? Could be useful to some big posts or long comment threads...

**Comment by talhasch** [comment]
i will check if it is possible on electron.

**Comment by talhasch** [comment]
implemented https://github.com/esteemapp/esteem-surfer/commit/d6097e3e42922f51414f355c8558b8f86ce8b3c3
