### ISSUE TITLE
issues/suggestions 1.0.9

### ISSUE THREAD

**Issue by viking-ventures** [esteemapp/esteem-surfer#131]
Firstly, the scheduler is showing the current date and time - not the date and time that the post is scheduled to be posted. 

Secondly, although I like the notifications thing (and just turned it off), it would be nice to have some sort of in between mode. I don't mind it telling me that people have upvoted me, but I can just imagine it next time I get @curied... 550 votes the other day! My poor computer will be a flood of blue notifications! 

Oh, one more thing - any chance of getting templates so I don't have to keep copy/pasting from my text file? (And I'd love an integrated spell-check - even though I often have arguments (and win!) with it, it's still a very useful tool.) 

Keep up the great work!

**Comment by fildunsky** [comment]
Regarding scheduler agree totally. It should show posting time (not draft saved time). Now it's confusing... 

@waybeyondpadthai wrotes:

> like I saved it at 8.20 but want it to be published at 15.30. Opening scheduler shows 8.20 instead of 15.30 and it's confusing...

![screen_shot_2561-07-22_at_08 20 51](https://user-images.githubusercontent.com/32987666/43048341-cdf2e46c-8dee-11e8-978f-3a4ef7e5c82e.png)

**Comment by talhasch** [comment]
All suggestions & bugs implemented/fixed except templates. Closing this one. We will follow templates under #213
