### ISSUE TITLE
Copied Text From Word Document Converted to Image File 

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#132]
Christa Schadt:
surfer - when we copy and paste the word document turns into a png!

> The user complained that anytime he tried to copy text from **Word document** and paste it to eSteem Surfer post editor page, the text would automatically be converted to image file (.png)

But from other text processor like notes etc. works fine.

![image](https://img.esteem.ws/b7fi5i7a53.jpg)

### Mac OS

**Comment by talhasch** [comment]
when you copied text from ms word, it adds screenshot of copied text to clipboard (what a feature lol). 
because of an image in clipboard, surfer starts file upload. 
added a condition to skip file upload if text in clipboard larger than 50 chars.

**Comment by feruzm** [comment]
I don't think it is good solution, especially if I want to copy past large content or prepare post somewhere else and copy into editor. Better would be disable image upload from clipboard.

**Comment by talhasch** [comment]
this is what i fixed :) editor detects if you pasting large text and skips file upload from clipboard.
check https://github.com/esteemapp/esteem-surfer/blob/master/src/directives/content-editor.js#L142

**Comment by feruzm** [comment]
looks good, just to double confirm... 
>i think no one uses more than 50 chars for a image file

are you referring to filename or filecontent? because image filecontent can be large if it is base64 string...

**Comment by talhasch** [comment]
referring to filename. javascript keeps file content another field (items) in clipboard object.

**Comment by feruzm** [comment]
ok, great!
