### ISSUE TITLE
Surfer CSS bug (div class pull-left + Bullets = mess)

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#133]
Whenever we are using div to pull image to the left side to wrap text around it gives visual bug for bullet lists if there are any in that paragraph.

Try this code in Surfer editor and check preview in right side:

```
<div class="pull-left"><img src='https://cdn.steemitimages.com/DQma2AjG3waQGAZPTQC85H9aJMFiARTs88Ly7jZRXgSdgpZ/misc.png'></div>

- **Miscellaneous stuff**. There are plenty of more news regarding eSteem you might be interested.
- The [first eSteem Meetup](https://steemit.com/esteem/@foways/the-first-esteem-meetup-explanation-of-rules-on-esteemapp-by-yandot-efa28912a1486) happened in Indonesia.
```

![screenshot](https://user-images.githubusercontent.com/32987666/42135677-cde86684-7d56-11e8-9378-05b7bfefcdf1.png)

**Comment by talhasch** [comment]
made some css improvements

![image](https://user-images.githubusercontent.com/1177676/43519956-f620ff20-9599-11e8-8a4e-186b82659f29.png)

**Comment by fildunsky** [comment]
Can we move these dots right away from the image for 5px more?

**Comment by talhasch** [comment]
because of previous element flotet to left ul elements doesn't apply margin or padding. 

i added margin to .pull-left and .pull-right classes.

adding more 5 px to .pull-left and .pull-right is not good approach because it is commonly used css helper.

**Comment by fildunsky** [comment]
Is it a bug or feature? :)

```
<div class=pull-left>https://img.esteem.ws/1oxcrdqima.jpg</div>
<div class=pull-right>https://img.esteem.ws/j5odz7lcic.jpg</div>
```

This code in Surfer:

<img width="1215" alt="2018-08-02 22 02 23" src="https://user-images.githubusercontent.com/32987666/43604985-c4b32f38-969f-11e8-9581-1a5ad5969d04.png">

Same code in Steemit/Busy:

<img width="679" alt="2018-08-02 22 01 34" src="https://user-images.githubusercontent.com/32987666/43604943-aca8314a-969f-11e8-97c4-e87ed523e787.png">

User reported that said it started to render like that after recent update...

**Comment by talhasch** [comment]
its a bug -_-
