### ISSUE TITLE
.phishy CSS bug

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#134]
@ijmmai wrotes

> Some time ago I asked for the .phishy class to be added, as this is also in use on steemit.com. And you did, which is great. Unfortunately you implemented it in a rather unusual way.
Instead of 
`.phishy {color: red;}` you used `div.phishy {color: red;}`
It works, but there is a problem when more HTML tags are used.

```
<div>
  <center>
    <h2>My text in red</h2>
  </center>
</div>
```

Is the correct way of using HTML tags, but now the text is not red.

Changing it to

```
<center>
  <h2>
    <div>My text in red</div>
  </h2>
</center>
```
makes it work but that is not the correct way to use HTML tags.
Is it possible to change it in the next version?

**Comment by talhasch** [comment]
removed div. restriction from css. you can add phishy class to every element you want. it makes element's text color to red.
