### ISSUE TITLE
Feed: No bold for post titles in Windows/Linux

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#136]
![headers_windows](https://user-images.githubusercontent.com/32987666/43412339-994483e0-9435-11e8-87ef-8ceb9a027299.png)

**Comment by fildunsky** [comment]
Same thing on Ubuntu 18.04

![ubuntu_same](https://user-images.githubusercontent.com/32987666/43413163-f51249ee-9437-11e8-9d3d-a781c00d8c7d.png)

**Comment by talhasch** [comment]
Houston we have a problem with helvetica font

### Helvetica

|   Osx	|	Win	|   Linux	|
|	------------	|	------------	|	------------	|
|	      <img width="486" alt="helvetica-mac" src="https://user-images.githubusercontent.com/1177676/43540703-21c2e580-95d1-11e8-92f2-e1be1674d33c.png">  	|	   <img width="500" alt="helvetica-win" src="https://user-images.githubusercontent.com/1177676/43540731-34031530-95d1-11e8-8671-ea4b6cea870a.png">     	|	    <img width="467" alt="helvetica-linux" src="https://user-images.githubusercontent.com/1177676/43540761-4580a8c2-95d1-11e8-8e5c-44b59eb7e47d.png">	|

Osx makes helvetica automatically semi bold but others dont. 

### Roboto


|   Osx	|	Win	|   Linux	|
|	------------	|	------------	|	------------	|
|	    <img width="492" alt="roboto-mac" src="https://user-images.githubusercontent.com/1177676/43540803-672406c2-95d1-11e8-869e-4a40323751c5.png">    	|	    <img width="483" alt="roboto-win" src="https://user-images.githubusercontent.com/1177676/43540831-75c359f8-95d1-11e8-93a2-2ea4451df6e9.png">   	|	    <img width="510" alt="roboto-linux" src="https://user-images.githubusercontent.com/1177676/43540852-82bd175c-95d1-11e8-8e7b-0f94a46bf54d.png"> 	|


I think we have to switch to roboto font.


You can check it from https://output.jsbin.com/dogehayuqi

**Comment by feruzm** [comment]
@talhasch good find, so issue was font 👍 let's fix it next week with #139
