### ISSUE TITLE
Autoupdate feature seems to be broken on Linux

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#137]
I am using Ubuntu 18.04 and have to update the app manually every time. I just have no notification saying there is an update...

**Comment by talhasch** [comment]
i forgot to mention before but unfortunately electron auto updater does not support Linux :( https://electronjs.org/docs/api/auto-updater#platform-notices

**Comment by fildunsky** [comment]
Okie, Linux Geeks could update it manually then :)
