### ISSUE TITLE
Editor preview wrong lists numbering

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#138]
Creating lists like this

```
1. Item
2. Item

Divided by some other texts or images

3. Item
```

Gives wrong numbering in post preview of Editor page

![bug](https://user-images.githubusercontent.com/32987666/43471201-0f8744ee-94f3-11e8-8a58-1411e2360330.png)

**Comment by feruzm** [comment]
It is likely because of extra lines, if you remove lines from both side of image link, will that solve this issue?

**Comment by talhasch** [comment]
yeah @feruzm right. @fildunsky it starts counting from 1 again because there are a line before image tag. not valid markdown. you should remove line before image.
