### ISSUE TITLE
Surfer Navbar visual improvements

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#139]
I've made couple of tweaks. Not sure if we need to go deeper for second variant yet. But for now we could at least try first variant (make search box larger and lighter by changing the button color to white and removing visual division between button and search field).

![search](https://user-images.githubusercontent.com/32987666/43521132-c994cd7a-959d-11e8-8482-5b82ea1d671f.png)

### Second variant

This I am not sure. Just some suggestions. What do you say?

- Move `Discover` to small arrow inside the search field since it's related to search thematics
- Change `Wallet` to credit card or wallet icon
- Shorten `Token Exchange` to `Exchange`
- Maybe swap search and wallet+exchange places

![search2](https://user-images.githubusercontent.com/32987666/43521131-c9734c9a-959d-11e8-89e1-5d1872eb761b.png)

**Comment by feruzm** [comment]
I like 2nd look, maybe we should try it out, since it is just matter of moving and resizing items, i think it should be simpler change. Wallet: let's keep Wallet word without icon for now. All other changes looks great...

**Comment by talhasch** [comment]
i like 2nd too

**Comment by fildunsky** [comment]
Great, glad you support my initiative! Thank you very much, guys! I've just tweaked it a little bit more...

![search3](https://user-images.githubusercontent.com/32987666/43538286-3fbecb3c-95ca-11e8-87d7-9158ead307de.png)

- Here theme switch icon is 50% transparent here comparing to original Surfer now so it takes less attention.
- Even larger search field

**Comment by talhasch** [comment]
even better

**Comment by fildunsky** [comment]
This is our baby :) I love spending time tweaking it here and there and enjoy each release update :)

**Comment by fildunsky** [comment]
By the way, one more thing before we go is that back button. It's so bold and unattractive now. Lets use same style as upvote and maybe even without circle...

![search3](https://user-images.githubusercontent.com/32987666/43575757-495bc39e-9650-11e8-86ef-8748cab1c5a3.png)

**Comment by fildunsky** [comment]
Could we also please add options in the app settings to switch off `Top posts` and `Similar posts` features if it's not too time consuming to code? It will give users the choice to set the Surfer as they want. More loyalty...

**Comment by talhasch** [comment]
yes, we can add.

**Comment by talhasch** [comment]
@fildunsky did you check new look of navbar?

**Comment by fildunsky** [comment]
@talhasch Yeah, looking perfect!
