### ISSUE TITLE
Horizontal scroll using minimum window size in Wallet

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#141]
Other pages looks okay but this one adding the scroll to the bottom.
<img width="1112" alt="horisontal_scroll" src="https://user-images.githubusercontent.com/32987666/43569784-2f3cbe64-9641-11e8-871d-e6afba80d8a8.png">

**Comment by talhasch** [comment]
i have never came across with this issue but add some css to prevent
