### ISSUE TITLE
Unclaimed rewards notification badge

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#143]
Would be super handy to see red notification on top of Wallet menu whenever there is an unclaimed rewards in your wallet.

![wallet_badge](https://user-images.githubusercontent.com/32987666/43777298-037577e4-9a5b-11e8-9fe1-20164452339f.png)

It could be just a small red dot `8px` diameter size and `#ff0000` color.

**Comment by talhasch** [comment]
done @fildunsky

**Comment by fildunsky** [comment]
Looking awesome! Love it!
