### ISSUE TITLE
Night style css needs small tweak

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#144]
When using 3 ` symbols for the codes samples they looks fine in day mode

<img width="1792" alt="2018-08-07 17 25 02" src="https://user-images.githubusercontent.com/32987666/43781988-ef889548-9a66-11e8-9f10-e6c42bca9c6c.png">

but looks faded in night mode

<img width="1792" alt="2018-08-07 17 24 58" src="https://user-images.githubusercontent.com/32987666/43781989-efdb8d7a-9a66-11e8-8c76-a6bef52afe60.png">

**Comment by talhasch** [comment]
add some css to format <pre> (3 `) elements

<img width="1112" alt="ekran resmi 2018-08-08 18 15 06" src="https://user-images.githubusercontent.com/1177676/43846454-0c9235d8-9b37-11e8-9f57-6e625bc612b5.png">
<img width="1112" alt="ekran resmi 2018-08-08 18 15 09" src="https://user-images.githubusercontent.com/1177676/43846455-0cb954ce-9b37-11e8-8ce2-7e131acf947d.png">

**Comment by fildunsky** [comment]
Looking very nice! ❤️

**Comment by fildunsky** [comment]
<img width="659" alt="2018-08-08 18 17 32" src="https://user-images.githubusercontent.com/32987666/43846660-8b0b76ea-9b37-11e8-8db6-1a996f9cf894.png">

Could we also remove that lines in between table rows in wallet? Both in night and day modes...

**Comment by talhasch** [comment]
sure wa can
