### ISSUE TITLE
Steempress images not showing as post cover previews

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#145]
<img width="1167" alt="2018-08-08 15 15 21" src="https://user-images.githubusercontent.com/32987666/43836431-05de1680-9b1e-11e8-97fb-7b952cab4d6e.png">

It's strange because everything else is looking fine but looks like posts done via steempress client not showing image preview at all.

They are using such a codes to display images:
`https://steemitimages.com/0x0/https://cdn.steemitimages.com/DQmRxQb1QA1FaJX3uG8sohB1JxhQ1Nds9sdWx4UHfCuhCPo/meural_hong_creative_crypto.gif`

`https://steemitimages.com/0x0/https://cdn.steemitimages.com/DQmVAC9PxvfqNv1YLez1fUK2pwxGx2hXcJiLazy8s4hNzQK/creative_crypto_submissions.png`

Maybe it's because of `0x0` in the urls?

**Comment by talhasch** [comment]
it was unexpected behaviour of steem. json_metadata field contains empty images. fixed.

**Comment by fildunsky** [comment]
Cool! Steempress posts are now looking fine!

This strange image also is not showing a post preview (posted from elegance):
`https://steemitimages.com/0x0/https://scontent-frx5-1.cdninstagram.com/vp/2574f7599cab85bdc1f4117277f3a245/5BF551B9/t51.2885-15/e35/37974456_2019475444751577_1101065830411534336_n.jpg?_nc_eui2=AeG2yURjdRyloOBtO2_6XvwtYAOIyowIgXLp7EmLvoi58pR3s29fFrgG9MoV7JDeFia-BVkyO7PGh5ACPrEYitZn`

**Comment by talhasch** [comment]
@fildunsky pls can you share post link or author name?

**Comment by fildunsky** [comment]
It's there https://steemit.com/elegance/@daio/well-that-s-my-handsome-canvas-oil-poseidon

**Comment by talhasch** [comment]
compared elegance's post previews with steemit. they are same. maybe it was temporary issue.

**Comment by fildunsky** [comment]
I believe it's related to filename from instagram. Maybe it's too long? Steemit shows fine but Surfer can not fetch it in post preview.

File name: `https://steemitimages.com/0x0/https://scontent-frx5-1.cdninstagram.com/vp/2574f7599cab85bdc1f4117277f3a245/5BF551B9/t51.2885-15/e35/37974456_2019475444751577_1101065830411534336_n.jpg?_nc_eui2=AeG2yURjdRyloOBtO2_6XvwtYAOIyowIgXLp7EmLvoi58pR3s29fFrgG9MoV7JDeFia-BVkyO7PGh5ACPrEYitZn`

<img width="1223" alt="2018-08-22 00 21 45" src="https://user-images.githubusercontent.com/32987666/44429856-90a74880-a5a1-11e8-820c-ad7c820e60e5.png">

Post link https://steemit.com/elegance/@daio/well-that-s-my-handsome-canvas-oil-poseidon
