### ISSUE TITLE
Delegate issue

### ISSUE THREAD

**Issue by branhmusic** [esteemapp/esteem-surfer#146]
I used the Delegate feature to delegate some steem power from my @branhmusic account to another user @brianhphotos on steemit yesterday, which worked fine. Shortly after, I delegated some more SP to the same @brianhphotos user account, expecting this to be added to the first amount but instead the first amount of 914 was overwritten with the second amount of 193 ( see the attached images )
![branhmusic_171412](https://user-images.githubusercontent.com/42294619/43991266-0e868bb0-9d61-11e8-8a5a-7ac22a43aa8c.jpg)
![brianhphotos_171025](https://user-images.githubusercontent.com/42294619/43991267-0ea341e2-9d61-11e8-97de-ccbf53e9002c.jpg)

From my @branhmusic account I then tried to undelegate the steem hoping it would return it all back to me. It removed the 193 of delegated steem from @brianhphotos and left my @branhmusic account with a delegated sp balance of -914.

So the end result is that @branhmusic appears to be delegating 914 SP but @brianhphotos has no delegated steem.

Please could you look into this with a view to fixing my @branhmusic  delegated SP balance back to 0 (zero).

Many Thanks
Brandon Hill

**Comment by feruzm** [comment]
Hey Brandon,
Delegation always overwrites existing delegation, meaning if you have delegated 10 SP and again delegated 15 SP to same account, final delegation will be 15 SP, not 25 SP. As for returning SP after undelegation, it will happen automatically within 7 days because there is cool-down period of 7 days.

**Comment by branhmusic** [comment]
Thanks for explaining this to me Feruzm - I didn't realize you have to wait 7 days and thanks for getting back to me so quickly.
