### ISSUE TITLE
Wrong post previews for dtube/dlive videos

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#150]
Example @acromott account

### Steemit

<img width="984" alt="2018-08-22 00 17 38" src="https://user-images.githubusercontent.com/32987666/44429648-cac41a80-a5a0-11e8-8e1a-2bdd551adf3a.png">

### Surfer

<img width="1223" alt="2018-08-22 00 18 03" src="https://user-images.githubusercontent.com/32987666/44429664-ddd6ea80-a5a0-11e8-97fb-224f7cac877e.png">

**Comment by talhasch** [comment]
fixed on last release
