### ISSUE TITLE
Search/URL field is cutting long links

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#151]
If we paste long link like this one: https://steemit.com/esteem/@olesia/sinnabon-rolls-with-cinnamon-in-slovichny-sauce-it-is-simple-to-prepare-68dd7b456d355 in Surfer search field area it will be cut and it will not open that post.

**Comment by feruzm** [comment]
yeah need to fix that in v2. meanwhile @fildunsky try: @olesia/sinnabon-rolls-with-cinnamon-in-slovichny-sauce-it-is-simple-to-prepare-68dd7b456d355

**Comment by fildunsky** [comment]
@feruzm shortening the URL to @username/etc... works well for me :) I just created this issue in case we will forget to fix it in future.

**Comment by fildunsky** [comment]
This one is not opening even with shortening to @username :)

@fractal-team/jwildfire-esperiments-with-plugins-in-the-base-fractal-flowers-on-the-window-part-2-d410ce2b9c257est

**Comment by talhasch** [comment]
fixed with v2
