### ISSUE TITLE
"Login" icon on top left when logged out, appears as a "logout" icon typically seen other places

### ISSUE THREAD

**Issue by corkyk** [esteemapp/esteem-surfer#153]
The "Login" icon on top left when logged out, appears as a "logout" icon typically seen other places, not a "login" icon. Typically an arrow pointing at a "door" looks like logout not login. 

For comparison examples - see steemit/steempeak logout icons compared to this one, which are rectangles or "doors" with an arrow pointing into their center to indicate going out, it's my opinion, that this icon is misleading and confusing to even an experienced user like me (but maybe only because I am an experienced flat design UX/UI user who expects typical "standards" for UI elements.)

-SirCork

**Comment by fildunsky** [comment]
@corkyk  Thanks a lot for your suggestion. You are absolutely right, it's confusing now.

@talhasch Can we change that icon to https://material.io/tools/icons/?icon=power_settings_new&style=baseline ?

**Comment by fildunsky** [comment]
Done in Surfer 2!
