### ISSUE TITLE
Editor selection scrolling

### ISSUE THREAD

**Issue by bonustrack** [esteemapp/esteem-surfer#156]
On the editor when i try to select a text the textarea is scrolling to top making complicated for me to select a line

![selection](https://user-images.githubusercontent.com/16245250/48958586-a8bca880-ef92-11e8-924c-e52411907229.gif)

on macOS

**Comment by feruzm** [comment]
Thanks @bonustrack ! We have fixed it on `master` branch, update will be released on Monday. You will receive update notification inside Surfer app to easily update.

**Comment by bonustrack** [comment]
Great!
