### ISSUE TITLE
Unecessary permlink suffix?

### ISSUE THREAD

**Issue by bonustrack** [esteemapp/esteem-surfer#157]
I've posted an article and the permalink got a random suffix @steemscript/steemconnect-3-a-better-way-to-sign-63826a07f8f44est (see the **-63826a07f8f44est**) The post has been published from a draft. It would be cooler if Surfer don't add this extra chars on the end of the title.

**Comment by feruzm** [comment]
Thanks, this is to keep randomness on permlink as well as helps our curators to detect the links. Medium.com uses similar approach... 

Do you think it is discouraging you from sharing a link or makes url not attractive?

**Comment by bonustrack** [comment]
Yeah the url look less attractive, Medium does not seem to care much about the first part of the permlink for example this https://medium.com/byteball/b35964feee8e redirect to https://medium.com/byteball/bringing-identity-to-crypto-b35964feee8e perhaps i would prefer a url like @steemscript/63826a07f8f44est

**Comment by feruzm** [comment]
fixed with latest release 2.0.1
