### ISSUE TITLE
Tables with links are very low contrast in Night Mode

### ISSUE THREAD

**Issue by inertia186** [esteemapp/esteem-surfer#158]
Tables containing links are a little difficult to read, but not completely invisible.  Just needs a tweak.  Here's how it looks at the moment:

![image](https://user-images.githubusercontent.com/494368/49459084-15118600-f7a3-11e8-8283-cb13b5653d09.png)

Observed in version: `2.0.1`

**Comment by talhasch** [comment]
@inertia186 Thanks for feedback. fixed.
