### ISSUE TITLE
Suggestion: Find in Page

### ISSUE THREAD

**Issue by inertia186** [esteemapp/esteem-surfer#159]
*As a user reading a long post, I'd like to be able to perform a "find in page" workflow, so I can find a particular text pattern.*

Maybe ⌘F key binding could reuse the `search://` component but instead, it beocmes `search-in-page:`.  Also ⌘L key binding to start regular `search://` would also be nice.

**Comment by feruzm** [comment]
Thanks @inertia186! We have this on todo list 👍

**Comment by talhasch** [comment]
implemented https://github.com/esteemapp/esteem-surfer/commit/d6097e3e42922f51414f355c8558b8f86ce8b3c3 next release will include it.

**Comment by talhasch** [comment]
implemented with last release. closing.
