### ISSUE TITLE
Suggestions & Issues 

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#161]

**Comment by horpeyloaded** [comment]
- Add support for [Grammarly](https://www.grammarly.com/) in editor  
![grammarly](https://user-images.githubusercontent.com/34909705/49922906-3153a800-feb2-11e8-8c61-1ee82c67385a.png)

- There is a typo here…, it should be Could not connect to __
![](https://cdn.discordapp.com/attachments/417386914983968769/522673006338637844/Screenshot_1.png)
- Auto Refresh on every page

**Comment by feruzm** [comment]
* Grammarly is bit longer topic to discuss, it is against privacy and we shouldn't encourage our users to use it. Everything you type will/might be compromised.

**Comment by horpeyloaded** [comment]
@feruzm Thanks for elaborating.

**Comment by horpeyloaded** [comment]
### Wallet Improvement
- Clicking on **-SP** should show delegatees details.
- Clicking on **+SP** should show should show delegators details.

- Show power down with amount e.g. ( Next power down is 6days **554 SP**)
- Show correct **wallet value** similar to busy and SteemPlus

**Comment by horpeyloaded** [comment]
### Table Insert Mode
Table insert mode instead of the fixed 3*3. 
Users can input the number of rows and columns they want to use. Clicking the table icon shows a box which users can then input number of rows and columns.

**Comment by horpeyloaded** [comment]
@talha users can't connect to the listed servers or custom server address even if the server is working. Error: `Could not connect to server`.. I'm also facing this issue. 
Some people can only connect to one server but as for me none, please look into this for later releases.

**Comment by horpeyloaded** [comment]
Head push notification / notification when favorite authors publish new posts
