### ISSUE TITLE
Application will not update.

### ISSUE THREAD

**Issue by dalton-109** [esteemapp/esteem-surfer#162]
I just downloaded the application for the first time.. and I cannot get it to update. 
The download just stays at 0%.
I have deleted and reinstalled the app multiple times. Same issue.

<img width="1020" alt="screen shot 2018-12-12 at 10 52 38 am" src="https://user-images.githubusercontent.com/45826694/49882748-458a9d00-fdff-11e8-9d1b-4c6556349a96.png">

**Comment by horpeyloaded** [comment]
That might be error with V2.0.0. Download the latest V2.0.2 from this direct link https://github.com/esteemapp/esteem-surfer/releases/download/2.0.2/esteem-surfer-2.0.2.dmg

**Comment by dalton-109** [comment]
Thanks so much for the quick reply!
