### ISSUE TITLE
Support links without HTTP/S prefix

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#166]

**Comment by horpeyloaded** [comment]
I meant Surfer should recognize links without http or https prefix.

google.com should work like https://google.com or http://google.com

did you get it @talhasch ?

**Comment by talhasch** [comment]
i think implementing this feature is not good idea because steemit and busy does not support urls without scheme prefixes. 

Check these out:

https://steemit.com/esteem/@chrisbolten/test-post-635748d16ed9fest

https://busy.org/@chrisbolten/test-post-635748d16ed9fest

@feruzm @horpeyloaded 


And honestly i don't see any beneficial point of adding it since people are used to use urls with schemes.

**Comment by horpeyloaded** [comment]
Steemit supports URLs without scheme @talhasch…  Steemit automatically adds https to links without https scheme. This is the reason why GK sent PL to Steemit to support esteem:// scheme

**Comment by horpeyloaded** [comment]
Steemit supports URLs without scheme @talhasch…  Steemit automatically adds https to links without https scheme. This is the reason why GK sent PL to Steemit to support esteem:// scheme

**Comment by talhasch** [comment]
did you check links i attached? and what is GK and PL?

**Comment by talhasch** [comment]
do you mean markdown links like [google](google.com) ?

**Comment by horpeyloaded** [comment]
Ooh! I see. This youtube.com/gaming.

This is not what I mean, That is not a link just text add it this way `[test](youtube.com/gaming)`

If you try that on Steemit, it works fine and steemit automatically adds https but on Surfer it does not work. 

## The problem is with Markdown

**Comment by talhasch** [comment]
ok

**Comment by horpeyloaded** [comment]
Yup, you got it. I mean this `[google](google.com)`

**Comment by horpeyloaded** [comment]
Sorry for the confusion, I didn't explain it well.

**Comment by talhasch** [comment]
its ok. np.

**Comment by horpeyloaded** [comment]
This will help

<img src="https://i.ibb.co/PTVnW9K/deeplink.gif" alt="G-20190115-1159004">

https://i.ibb.co/PTVnW9K/deeplink.gif

**Comment by talhasch** [comment]
implemented. closing.
