### ISSUE TITLE
Suggestion: Emoji

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#170]
![2018-12-02 10_18_15-esteem surfer](https://user-images.githubusercontent.com/34909705/49782241-ed2ba080-fd15-11e8-8df6-e5b52ee8b990.png)

**Comment by talhasch** [comment]
Emoji support coming with 2.0.4 
![image](https://user-images.githubusercontent.com/1177676/51125935-c2070600-1819-11e9-96a9-1b8cfa5a049c.png)
