### ISSUE TITLE
Suggestion: Footer

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#172]
![2018_11_28_14_15_12_esteem_surfer](https://user-images.githubusercontent.com/34909705/49782326-2cf28800-fd16-11e8-90e7-62f2bd076bbe.png)

**Comment by talhasch** [comment]
it is not good idea to make footer full of numbers. what do you think @fildunsky ?

**Comment by horpeyloaded** [comment]
@fildusky said, it could be an hideout or an option for users to enable or disable it (switch button).

**Comment by fildunsky** [comment]
I still can not even get used to that long blue and green bars with VP & RC and dreaming to get that back to old Surfer 1.x style there with just small battery icon and text. But these additional stuff we can add as a tooltip when user hovers a mouse on that battery icon for example...

**Comment by feruzm** [comment]
@fildunsky suggest or link edits/mockups for change... having battery and hover effect works for me

**Comment by fildunsky** [comment]
Can you check https://zpl.io/VQKXQeW ?

**Comment by talhasch** [comment]
this one already completed. closing.
