### ISSUE TITLE
Surfer in Maximize or Full Screen

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#175]
The spaces after Top Posts are left blanked. Can there be a button to enable or disable Top Posts or any other info that can be added. It looks cool if not in Full Screen though.
![2018_12_06_09_13_58_esteem_surfer](https://user-images.githubusercontent.com/34909705/49782665-6d9ed100-fd17-11e8-9b58-fdf2977d4385.png)

**Comment by talhasch** [comment]
i dont think it could be a useful feature. what do you think @feruzm ?

**Comment by feruzm** [comment]
for now we can add more space between cards and/or fetch top 7 posts and allow horizontal scrolling if window size is small

**Comment by talhasch** [comment]
ok
