### ISSUE TITLE
Suggestion: Table Insert Mode

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#183]
Table insert mode instead of the fixed 3*3. 
Users can input the number of rows and columns they want to use. 

Clicking on the **table icon** gives a two boxes for inserting number of rows and columns.

**Comment by talhasch** [comment]
Column options are coming with 2.0.4 
![image](https://user-images.githubusercontent.com/1177676/51125501-b6670f80-1818-11e9-9f94-acde3bfa1576.png)
