### ISSUE TITLE
FetchError:request to https://rpc.steemliberator.com/ failed

### ISSUE THREAD

**Issue by johnnysosa** [esteemapp/esteem-surfer#187]
FetchError:request to https://rpc.steemliberator.com/ failed, reason:certificate has expired

**Comment by talhasch** [comment]
error message is quite clear. they haven't renew ssl certificate. maybe we should remove this address from list. what do you think @feruzm ?

**Comment by feruzm** [comment]
yes, we can do that. done!

**Comment by johnnysosa** [comment]
But the error continues in version 2.0.4 and I don't know, if that's what causes me not to be able to see my profile and other options correctly. Everything is half done; however, I have been able to use the application to create my post and see the notifications.

**Comment by horpeyloaded** [comment]
@johnnysosa please try to connect to other servers lile api.steem.com, esteem, you will get a green thick pop up if it's connected. Can you also provide a screenshot of the full settings page of your Surfer app.
