### ISSUE TITLE
Changelog automated window/page

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#19]
After initial release and #11 

we can have changelog page similar to bottom image

![](https://cdn.discordapp.com/attachments/426815654277152779/426819965627400207/unknown.png)

where user gets information about changes, all data can be fetched from backend (images and content can be controlled and app can pull data if there is new entry) or something similar, better approach if you have any thoughts on this, let me know @talhasch.

**Comment by talhasch** [comment]
@feruzm  i think the change log page we have used for last 4 releases is more convenient than this one. what do you think?

**Comment by feruzm** [comment]
For now it is ok, but in future when we get to bigger release cycles where our releases go out every 2 or 3 months then we will need better changelog viewer with proper topup/modal screen and has details of each change with screenshot or with video.
