### ISSUE TITLE
Comments tab doesn't work + v2.0.5 says it's v2.0.4

### ISSUE THREAD

**Issue by economicstudio** [esteemapp/esteem-surfer#193]
Esteem surfer is very cool app! I've just used it for the first time today.

I've found two problems:

- "Comments" tab shows nothing. Other tab (Blog, Replies, Wallet) works fine.
- It says 2.0.4 in the status bar, while I installed with https://github.com/esteemapp/esteem-surfer/releases/download/2.0.5/esteem-surfer-2.0.5.dmg

![](https://user-images.githubusercontent.com/38183982/51935080-ffb08500-23fc-11e9-9a24-2ebb6fc6206b.png)

App version: 2.0.5 (might be 2.0.4, see above)
Version: MacOS 10.14.2 (Mojave)

**Comment by feruzm** [comment]
@economicstudio thanks for your report! we are investigating release of 2.0.5 why it is coming out as 2.0.4. We might have to re-upload files. I will notify you here to re-download to try again, in few minutes.

**Comment by economicstudio** [comment]
Thanks! what about comment tab? Wasn't it working with 2.0.4?

**Comment by feruzm** [comment]
Comments are working for me, maybe you had connection issue?! Hold on for new update for improvements, after that you can recheck comments section as well... thanks!

**Comment by economicstudio** [comment]
![](https://user-images.githubusercontent.com/38183982/51944450-fc74c380-2413-11e9-982c-0441e63e426a.png)

As I replied on steemit, version & sbd are fixed, but comments tab still doesn't work for me. all other tabs are working like a charm.

**Comment by economicstudio** [comment]
I've just also tested on win7, comments tab doesn't work either on win.

**Comment by economicstudio** [comment]
oops. win version also says it's 2.0.4

I installed with https://github.com/esteemapp/esteem-surfer/releases/download/2.0.5/esteem-surfer-setup-2.0.5.exe

**Comment by feruzm** [comment]
Thanks for more details... We will check what might be causing comments issue on your end. Have you tried to change Server/Node from Settings? 
I will update windows release manually now...

**Comment by economicstudio** [comment]
comments are working with different server, e.g., rpc.esteem.app or others. but not with api.steemit.com any chance that esteem surfer is using deprecated api? 
https://steemit.com/steemit/@steemitdev/upcoming-changes-to-api-steemit-com

I haven't had time to read the code. which apis are you using for getting comments?

Could you also make build possible so that I can debug/develop on my own? #196 Thanks!

**Comment by economicstudio** [comment]
btw, to see the problem of comments tab with api.steemit.com you may restart, i.e., changing from working server to api.steemit.com may still show comments. I guess that might be why you guys didn't have a problem.

**Comment by talhasch** [comment]
fixed. closing..
