### ISSUE TITLE
incorrect effective SP & powerdown amount

### ISSUE THREAD

**Issue by economicstudio** [esteemapp/esteem-surfer#197]
- Effective SP

Effective SP should exclude powerdown amount, but esteem includes it.

![](https://user-images.githubusercontent.com/38183982/51994566-fbda3c80-24a8-11e9-9120-68cf7eacb549.png)

![](https://user-images.githubusercontent.com/38183982/51994480-c1709f80-24a8-11e9-9877-ec7a53d468a0.png)

This is important for calculating correct voting value (if this feature will be added).

- Powerdown amount

While eSteem shows the powerdown amount separately at the bottom, which is very good, it also has the following problem.

Due to this "bug": https://github.com/steemit/steem/issues/3237, powerdown may take 14 weeks, not 13 weeks.

Even for the 14th week, withdrawal amount is still the same (i.e., very big), so `min` function is needed to determine the actual remaining withdrawal.

I'll submit PR.

**Comment by feruzm** [comment]
Good find, yes I agree power down amount should be taken out of vote calculation. We have vote calculation already so it should be considered, @talhasch. But total SP value I think showing up correctly, it is not effective SP per se but it is total amount of SP currently account holds, at any point if user decides to stop power down, they will have same amount of SP. Looking forward for PRs 👍  keep up the good contribution, we really appreciate it 😉

**Comment by economicstudio** [comment]
Thanks for your comment. I've just submitted PR.

Re total SP, people may have different opinions. But as shown in steemd, I think it's better to follow their practice. I personally prefer that way due to the name 'STEEM POWER', it's **POWER** from which most people think voting value is proportional to. Especially when approaching to the end of the powerdown cycle, e.g., after 10 weeks or so, the difference can be very huge. Busy also had such a problem with voting value due to that, which I fixed 😉

But if you really prefer not to exclude powerdown amount in the total SP, let me know, I'll change the code. But at least please think twice. It's **POWER** not asset :)

**Comment by feruzm** [comment]
I checked PR screenshot, it looks good to me, maybe you can add tooltip on last `-amount` saying that `Power down portion` or `Current power down amount` ?

**Comment by economicstudio** [comment]
Actually I already added tooltip, sorry I didn't upload that screenshot.

![](https://user-images.githubusercontent.com/38183982/52002064-eb31c280-24b8-11e9-9f24-e2bd736c2f63.png)

I used 'pending withdrawal' but let me know if you prefer different wording. Maybe 'Next power down amount'? for consistency with the message on the bottom?

**Comment by feruzm** [comment]
I like `Next power down amount`. Yes, it can be added into en_US.json in dedicated section and our translators will automatically be notified about new phrase.

**Comment by economicstudio** [comment]
Sure, I'll change it with en_US.json and update PR. Thanks!
