### ISSUE TITLE
delegationClicked doesn't work

### ISSUE THREAD

**Issue by economicstudio** [esteemapp/esteem-surfer#198]
![](https://user-images.githubusercontent.com/38183982/51996933-abb1a900-24ad-11e9-89ce-b27b836eaed7.png)

If clicked, a white blank page is shown, and no way to go back (Is there any keyboard shortcut for go back?)

https://github.com/esteemapp/esteem-surfer/blob/93599f413ca9c2c0920ec9fd28386837b22faaf1/app/components/Account.js#L1113

**Comment by horpeyloaded** [comment]
This also occurs when a user tries to power up Steem and also crashes app on Mac OS.

**Comment by feruzm** [comment]
It should show something similar to this: Could you double check and confirm if this issue still exist?
Thanks!

![image](https://user-images.githubusercontent.com/3015990/52546321-cc8bcf80-2dc6-11e9-8cf8-e13d9dd70c5e.png)

**Comment by economicstudio** [comment]
@feruzm It's working very well now!
