### ISSUE TITLE
Connection through a proxy

### ISSUE THREAD

**Issue by johnnysosa** [esteemapp/esteem-surfer#201]
Hello, greetings... my internet connection, generally, is through a proxy and I have observed that to esteem-surfer it is difficult to work in this scenario, the notifications and the option Drafts work well through the proxy, but the rest of the options do not.

Thanks

**Comment by talhasch** [comment]
@johnnysosa thanks for feedback. default server sometimes works slow. you can switch to our custom server https://rpc.esteem.app which works faster. you can change server on settings window. 
<img width="664" alt="ekran resmi 2019-02-04 11 49 34" src="https://user-images.githubusercontent.com/1177676/52198214-1b8baf00-2873-11e9-9936-215f58029398.png">

**Comment by feruzm** [comment]
in addition, we will have auto failover feature (from v2.2.6) so app will try to keep you always connected
