### ISSUE TITLE
[BUG Surfer 2.0.5] Upvoting time showing 19 hrs for all

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-surfer#208]
**Describe the bug**
Upvoting time is showing 19 hrs for all. Suppose if @someuser upvoted in my post 2 minutes ago then 2 minutes should display there but showing 19 hrs flat for all.

**To Reproduce**
1. Launch eSteem surfer 2.0.5.
2. In profile page select any blog and check upvoter list.
3. See the right side.

**Expected behavior**
In my one new post, i checked the upvoter list and suddenly saw that time is showing 19 hrs but should show 3 minutes.

**Screenshots or Video**

![surfer voting time](https://user-images.githubusercontent.com/36129744/52189454-b62dc300-285e-11e9-8112-7b7addd101b5.png)

**Smartphone (please complete the following information):**
 - Device: [Hp Laptop]
 - OS: [Windows10]
 - Version [10]

**Additional context**
Time syncing with the server is not proper.

**Comment by economicstudio** [comment]
I forgot to let you know this, but this may be related to this: https://github.com/steemit/steem/issues/3245

It's happening to steemd (show nothing), steempeak (second ago). what they're showing depends on how they handle null :)

So I think this isn't esteem's problem (especially considering that steemd has the same problem). probably dsteem library has a problem? based on I tried to figure out myself.

**Comment by economicstudio** [comment]
@face2face-utopian That's another well-know problem: https://github.com/steemit/steem/issues/3240

Due to the hivemind migration, many things seem unstable :(

**Comment by economicstudio** [comment]
@roadscape let me know in steemit/steem#3240 that this is hive issue: already discussed here: https://github.com/steemit/hivemind/issues/161

**Comment by talhasch** [comment]
Thanks for feedback @face2face-utopian As @economicstudio mentioned this problem is related to hive's backend problem. A temporary patch applied in order to fix it until hive's problem fixed.

**Comment by face2face-utopian** [comment]
Thanks a lot dear.
