### ISSUE TITLE
[BUG] More than 2 emojis in the title editor bring weird characters

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-surfer#212]
#### Project Information
* Repository: https://github.com/esteemapp/esteem-surfer
* Project Name: eSteem Surfer 2 – Steem Desktop Client

#### Expected behavior
My expectation was that I could add several smileys / emojis to the title of my post without any problems and without strange special characters.

#### Actual behavior
If you enter several smileys / emojis in the title of your post one after the other, strange characters appear from the second emoji. This only happens in the title of the post. In the post itself it works great. The video shows it quite well.

#### How to reproduce
Download the latest version of the Desktop Surfer app from Github. Install the software. Launch the app. Enter a pin. Switch to the editor and enter smileys several times in the title. For example the Muscle Emoji from the Screen Record.

* Browser/App version: Latest App Version 2.0.5
* Operating system: Mac OSX 10.14

**This Issue is also on the Windows Application. Just downloaded a fresh Copy to my Notebook to check that out. Also the Problem. Mobile Version works fine.**

#### Recording Of The Bug
![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/35930080/52371903-02435800-2a57-11e9-955b-8fb31aa18f1a.gif)

#### GitHub Account
https://github.com/louis88-steemit

**Comment by talhasch** [comment]
nice finding @louis88-steemit We'll fix it soon.
