### ISSUE TITLE
Steemconnect notes

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#214]
On steem connect login mention/add following text.

`Note: Steemconnect may charge some fees from your reward transactions`

ref: https://steemit.com/steemconnect/@fabien/major-incoming-changes-on-steemconnect

**Comment by economicstudio** [comment]
hope fee won't happen.

Steemit already supported 8.7K SBD so probably okay for a while.
And maybe forever :) https://steemit.com/kr/@blockchainstudio/drugwars-may-help-free-steemconnect

**Comment by talhasch** [comment]
note added. closing this one
