### ISSUE TITLE
Currency settings is inconsistent in search results. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-surfer#224]
#### Expected Behavior
By default, the currency settings on Esteem surfer is US dollars. But, I could change that to my preferred currency. 
I expected that if I changed the currency settings, the new currency will be consistent in all parts of the app where currency is displayed,
NB; Not inside posts though.

#### Actual Behavior
On search results of posts, the currency is displayed in default US dollars. 

#### How to reproduce

- Goto settings page
- Change currency settings to your preferred currency
- Make a search on the app.(Don't search for users). You can search a word instead.
- Check the currency on the preview of the post.

#### Screenshot

![curre](https://user-images.githubusercontent.com/40593824/53680096-78de1900-3cd6-11e9-8b74-f44acd1ca0b5.png)

**Comment by talhasch** [comment]
Thanks for feedback @HarryHeights This fixed on last release.
