### ISSUE TITLE
SUGGESTION: A search bar would come in handy on followers/following page. Sorting would also be great

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-surfer#226]
I love the grid/card display of the followers/following list. Amazing job done I must say. 

I think a search bar would come in handy though. Instead of scrolling and surfing through the list, I could just easily search for them.

Sorting is another thing that would come in handy on that page. I don't how the list is currently sorted. 
It is in a sort of random, shuffled order. 
I'd ideally love to sort the list in alphabetical order or other parameters.

Here's a mockup;

![folll](https://user-images.githubusercontent.com/40593824/53680563-9f538280-3cdd-11e9-9401-dd548be24b19.png)

**Comment by talhasch** [comment]
Thanks for suggestion @HarryHeights Search in followers/following window feature is already in our development list. Will be implemented soon.

**Comment by talhasch** [comment]
Searching in followers/following users implemented with ver 2.0.7. For sorting, there is no endpoint on steem. Not possible for now. Maybe in future...
