### ISSUE TITLE
Search-in-page doesn't work.

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-surfer#227]
#### Expected Behavior

I expected that I could find a word in a page. According to the updates made in the latest release, this action should be possible. 

#### Actual Behavior
I tried to use the feature by using the key command `ctrl` + `F` and the search in page box doesn't come up. Sometimes, it did, other times it didn't. 
It's like a hit and miss thing.

#### How to Reproduce

- Open a post either on the feed or anywhere
- Press the key combination to toggle on in-page search which is;  `ctrl` + `F`
- See error

#### Test Enviroment

Device; HP Pavilion DV7
OS; Windows 7 Professional

**Comment by talhasch** [comment]
Thanks for reporting @HarryHeights Will be fixed next ver. we release soon.
