### ISSUE TITLE
[Bug] sc2-sdk error in 2.0.6

### ISSUE THREAD

**Issue by dalton-109** [esteemapp/esteem-surfer#229]
I have two accounts logged in. I am able to redeem rewards, upvote, comment, etc with @2nd account. I cannot do any of that with my @1st account.

**Comment by horpeyloaded** [comment]
Please log-out and log-in account when you experience this. It means your SteemConnect session has expired.

**Comment by LHuntoon** [comment]
I have this issue no matter what I do. I've tried to log out and back. It has been like this since 2.0.3 for me. I keep updating. I have completely uninstalled and no luck.

**Comment by feruzm** [comment]
@LHuntoon Which key are you using for login?

**Comment by LHuntoon** [comment]
Sorry, I didn't see this message until now.  I use my posting key.
