### ISSUE TITLE
Update from 2.0.5->2.0.6 doesn't work

### ISSUE THREAD

**Issue by economicstudio** [esteemapp/esteem-surfer#231]
I was actually impressed by the existence of the version update feature, but it didn't work properly.

it worked well until the progress bar is fileed and rebooting, but it shows a blank page as below.

![](https://user-images.githubusercontent.com/38183982/54633157-84239980-4a77-11e9-911f-1251be389e0a.png)

ps. This may not be the problem of the update itself. Installing https://github.com/esteemapp/esteem-surfer/releases/download/2.0.6/esteem-surfer-2.0.6.dmg manually has the same problem.

2.0.5 still works well.

Version: 2.0.5->2.0.6
OS: MacOS Mojave (10.14.3)

**Comment by horpeyloaded** [comment]
@economicstudio The v2.0.6 was recompiled so it should be fixed, could you please try again?

**Comment by economicstudio** [comment]
@horpeyloaded Thanks! It's working now!
