### ISSUE TITLE
[Bug] eSteem Surfer 2.0.6 Transfers in notifications are not displayed correctly

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-surfer#233]
#### Project Information
* Repository: https://github.com/esteemapp/esteem-surfer
* Project Name: eSteem Surfer Desktop Application
* Publisher (if applicable): esteemapp 

#### Expected behavior
My expectation was that the notifications would be displayed correctly with all information when a transfer made to a user.

#### Actual behavior
Currently, the version 2.0.6 of eSteem Surfers displays curiously empty content. If a user sends another user an amount in Steem, an empty notification is displayed at the place of the notification. At least the value of the transaction the user received should be displayed here. 

#### How to reproduce
Send a user who also uses the eSteem Surfer app a sum of Steem. The user gets the notification as shown on the screenshots. 

* Browser/App version: 2.0.6 latest
* Operating system: MAC OS 10.14 

#### Recording Of The Bug
https://i.imgur.com/8agSTqQ.gif

![image](https://user-images.githubusercontent.com/35930080/55223933-9f2ca100-520f-11e9-8a93-c6e289156fef.png)

![image](https://user-images.githubusercontent.com/35930080/55224391-b9b34a00-5210-11e9-9491-b1e4b771aa73.png)

#### GitHub Account
https://github.com/louis88-steemit
Steem Account: louis88

**Comment by feruzm** [comment]
Yes, new update is on the way which already fixes it! thanks for report!

**Comment by talhasch** [comment]
fixed on last release
