### ISSUE TITLE
Suggestion: Show 10% Beneficiaries

### ISSUE THREAD

**Issue by michelangelo3** [esteemapp/esteem-surfer#234]
Show information when creating a post, that 10% Beneficiaries will be set for @esteemapp.

I think it is a "bad-karma" if this is done hidden, user confidence is important and should not be lost.

**Comment by horpeyloaded** [comment]
It’s written publicly in eSteem FAQ, nothing is hidden. It’s necessary for users to read FAQ or ToS before using any product.

**Comment by michelangelo3** [comment]
> It’s written publicly in eSteem FAQ, nothing is hidden. It’s necessary for users to read FAQ or ToS before using any product.

I disagree. That would mean, who doesn't read the FAQ is his own fault? I find that position disappointing.

Also, what FAQ do you mean? There is no link on https://esteem.app, no link on the download page, no reference in the playstore. I only found these [here](https://steemit.com/esteem/@good-karma/esteem-frequently-asked-questions-faq-eys44lmimx)  and 5% is written there.

I hope there will be another answer with more understanding.

**Comment by horpeyloaded** [comment]
Does Dtube, Oracle-D, and SteemPress show you that on their platforms creating a post?

**Comment by michelangelo3** [comment]
I'm not using Dtube and SteemPress.

I have no problem supporting eSteem with 10%. But i don't like it, when 10% Beneficiaries are set without my knowledge. Meanwhile I found the FAQ again and the explanation, so I am a little reassured. Unfortunately I didn't notice it when I read it for the first time. So, thanks for the hint.

But, not everyone reads the FAQ - my suggestion is for a better transparency. I think this is important.

**Comment by feruzm** [comment]
We have decreased beneficiary to 3% from 10% and in future we might even remove it. So follow `@esteemapp` for up to date information, we keep our users informed about every changes, so you won't miss it.
