### ISSUE TITLE
Cut does not work on editor

### ISSUE THREAD

**Issue by darewealth** [esteemapp/esteem-surfer#235]
### Describe the bug
I was trying to cut some part of my texts while I was typing in the sufer editor, but I encounter a wierd behavior. The cut text does not cut. It works the same like copy and paste.

### To Reproduce

* Open the app

* Go to the editor and type anything 

* Cut what you type and paste it 

### Expected behavior
I was expecting the cut texts should be completely off the editor, and shouldn't work like copy.

### Recording Of The Bug

![esreem](https://user-images.githubusercontent.com/36304257/55920048-33274100-5bf0-11e9-89e2-3b5084804591.gif)

### Test Environment

Device; HP pavilion

OS; Windows 8

App version [2.0.6]

**Comment by talhasch** [comment]
@darewealth thanks for reporting. We've revamped editor context menu. And fixed the issue. Will be available with new release soon.
