### ISSUE TITLE
Problems with estimated wallet amount. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-surfer#236]
#### Describe the bug.

I set my currency to display in my local currency which is the 'Nigerian Naira' (NGN).  When I check my wallet, the estimated amount is still shown in USD equivalent but with the Naira symbol. The issue is consistent with all other currencies. 

#### Steps to reproduce

- Goto you wallet on esteem surfer just to check your estimated wallet amount. This info is located here;

![estimated](https://user-images.githubusercontent.com/40593824/56096818-bf817e80-5ee4-11e9-87af-bfeadb11b083.png)
- From the image above, notice that my currency is set to bitcoin. But the value still shows as 1,065. Which is incorrect.
- To change currency; goto settings and change to a different currency. 
- Go back to your wallet and see the error. 

#### Expected Behavior 

Well, my expected behaviour is simple. I expected that my wallet will be shown in my currency equivalent. 

#### Test Environment

- Esteem surfer v2.0.7

#### Screen recording.

I don't think it's necessary, but here it is;

https://youtu.be/Io35v8vB50g

**Comment by talhasch** [comment]
Thanks for reporting @HarryHeights Will be fixed in next version.
