### ISSUE TITLE
Improvements to the user search feature

### ISSUE THREAD

**Issue by curtwriter** [esteemapp/esteem-surfer#237]
### Components 
Recently, eSteem releases a new update to its eSteem Surfer app for laptops and desktop devices running on the Windows and Linux operating system. The eSteem Surfer 2.0.7 came with three major features, one of which was the user search feature in the following and followers listing.

### Proposal description
The recently added user search feature on eSteem Surfer has so far been a good addition, but I believe it needs some tweaking to be better. Currently, you will need to input the full username of the user and click on the search icon before you can get any results. But what if you are unsure of the right spelling of the name? You'd agree with me that usernames like @anggreklestan and @andrarchy could be hard to spell at a go. The latter has that part that sounds like the dragon magic word “dracarys” in the Game of Thrones and I may be tempted to use that at some point.

### Suggestion 
Improve the search feature on eSteem Surfer in such a way that the user immediately begins to get suggestions after typing in the first letter of the user name. Adding the second letter should narrow down your search results a bit and it continues that way till you are able to see the user you looking for.

### Mockups/Examples
I have attached below mockups for my suggestion:

#### Image 1
The first picture shows how the present search looks like. Even after typing in the user’s full name, it does not come up until I click the search button.
![esteem Previous Search](https://user-images.githubusercontent.com/36970942/56489937-5d73db00-64db-11e9-8e53-9d62d80b9bec.png)

#### Image 2
The picture below is the mockup for my suggestion. Once you type in the first letter of the name, it brings up a list of all users whose names start with that letter. As you add more letters, the list is further narrowed down until you see your user.

![eSteem New Search](https://user-images.githubusercontent.com/36970942/56489959-6e245100-64db-11e9-961a-b370d3617ff0.png)

### Benefits
Like I mentioned in the proposal description, it will help the user in easily searching for other users despite not being very familiar with the spelling of their names. It also helps in eliminating the time it would take to do trial and error until you get the spelling of the username right.

**Comment by talhasch** [comment]
Thanks for suggestion @curtwriter We have implemented prefix filtering and typeahead search. Will be available next release soon.
