### ISSUE TITLE
[BUG] eSteem Surfer's Vote Count Function Does Not Work

### ISSUE THREAD

**Issue by curtwriter** [esteemapp/esteem-surfer#238]
**Project Information**
•	Repository: https://github.com/esteemapp/esteem-surfer
•	Project Name: eSteem Surfer Desktop Application
•	Publisher (if applicable): esteemapp

**Expected behavior**
My expectation was that the number of votes I received in the last 24 hours would increase as I receive more upvotes.

**Actual behavior**
Currently, the version 2.0.7 of the eSteem surfer just shows me 2 upvotes as being the number of upvotes I received in the last 24 hours which is quite ridiculous considering that I’ve received over 30 upvotes in the past 24 hours.

**How to reproduce**
Visit your profile tab of the eSteem Surfer app. By the left hand side, you’d see icons for post counts, number of upvotes received and others. If you have received upvotes in the past 24 hours, check your notification bell. My recording explains it better.
•	Browser/App version: 2.0.7 latest
•	Operating system: Windows OS 10

**Recording Of The Bug**
![eSteem vote count bug](https://user-images.githubusercontent.com/36970942/56524798-f4737e00-6541-11e9-88fa-4ecc504635a5.gif)

**Comment by talhasch** [comment]
Number of votes on profile page shows the user's votes they did in last 24 hours. Not they received.
