### ISSUE TITLE
[Bug] Wrong Thumbnail Image On Draft List

### ISSUE THREAD

**Issue by erikah1** [esteemapp/esteem-surfer#239]
**Bug Description**
Draft list is showing the last created draft's thumbnail image for all drafts. When saving a new draft, the thumbnail image changes for all drafts, the last draft's thumbnail image is shown for all drafts. 

**To Reproduce**
1. Go to Drafts
2. Create a draft 
3. Create another draft 
4. Close app 
5. Open app
6. Click Drafts

**Expected behavior**
Each draft should have its own thumbnail photo showing when looking at the draft list.

**Screenshots**

![esteem draft thumbnail 2](https://user-images.githubusercontent.com/47053627/57013671-489ef200-6c15-11e9-8eb7-263666318831.jpg)

Screenshot of my Draft list. 

![esteem 5](https://user-images.githubusercontent.com/47053627/57013813-edb9ca80-6c15-11e9-8e76-6dec354732f7.jpg)

I created a test draft with one photo. 

![esteem draft thumbnail 3](https://user-images.githubusercontent.com/47053627/57013687-5f454900-6c15-11e9-9408-9af9403d9b1c.jpg)

Screenshot of my Draft list after saving the new draft.

**Additional information**
The photos uploaded in drafts are not modified, only the thumbnail photos on the Draft list.

**Comment by talhasch** [comment]
Nice catch @erikah1 Thanks for reporting. It will be fixed in next version we release soon.
