### ISSUE TITLE
Esteem Surfer [ver 2.1.0 Web App Client] App gives error message and fails to publish post

### ISSUE THREAD

**Issue by Mistakili** [esteemapp/esteem-surfer#243]
### Description
When I click on "Post" I keep getting two error messages 
### Expected behavior
I expected it to publish my post 
### Steps to reproduce
Launch the app
Enter the post, click on "post"
### Devise used
HP Elitebook 8460p
Windows [8.1]
App version. Current version
### Screenshot to reproduce the bug

![bng (1).jpg](https://cdn.steemitimages.com/DQmRYMowfUSAKYNZmGJfqzpjeDoU6RZzADeQ5HnSKK7TPkM/bng%20(1).jpg)

![](https://cdn.steemitimages.com/DQmPnEXLxZoTmbXFhGzhNxPReAW9TySymz6SYrDvX1VdAYe/image.png)

App Github link - https://github.com/esteemapp/esteem-surfer

My Github link https://github.com/Mistakili

**Comment by talhasch** [comment]
Thanks for reporting @Mistakili  but this issue is not directly related to eSteem Surfer. May be a temporary blockchain issue. Closing...
