### ISSUE TITLE
Connect to Mobile

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#26]
Think about tab (after Wallet item) in profile page where it can offer QR code and/or quicker ways to connect account to eSteem Mobile

![image](https://user-images.githubusercontent.com/3015990/39629905-571c8daa-4fb6-11e8-9057-8ff5de41f605.png)

**Comment by talhasch** [comment]
Implemented @feruzm 

@fildunsky maybe we can make more stylish app qr codes?
![image](https://user-images.githubusercontent.com/1177676/41254767-1d4e4840-6dcd-11e8-8834-54bf743acb6e.png)

**Comment by fildunsky** [comment]
![qrs](https://user-images.githubusercontent.com/32987666/41256400-2358866a-6dd2-11e8-8f02-a1a90eeab834.png)
Cool! Maybe something like this? I've checked. QRs seems to be readable anyway.

**Comment by talhasch** [comment]
@fildunsky looking great!
