### ISSUE TITLE
Installation Request: Provide SHA256 Checksum Value

### ISSUE THREAD

**Issue by roleerob** [esteemapp/esteem-surfer#260]
For added security for your "customers," in downloading and installing your app, please consider adding the subject, to future releases.

Thanks!

**Comment by feruzm** [comment]
@roleerob thanks for inquiry, we already include those, check yml files on release, they all include sha512 checksum... https://github.com/esteemapp/esteem-surfer/releases/tag/2.2.0

**Comment by roleerob** [comment]
Okay, thank you @feruzm, for pointing that out.  I have not seen *.yml files before now.  Next time, I will hopefully remember!
