### ISSUE TITLE
Contacts or autofill on transfer pages

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#27]
have contact list or autofill on transfer pages, when user starts typing or focus on input, there should be recommended list of contacts/friends to quickly select or search without typos...

**Comment by horpeyloaded** [comment]
I love this feature @feruzm @talha. Additionally, portable (small) profile picture of the recipient can also be included beside the username 😉.

**Comment by talhasch** [comment]
implemented https://github.com/esteemapp/esteem-surfer/commit/03ecacc28734d867e43ff54a0008b0d09b86df65

**Comment by talhasch** [comment]
implemented with last release. closing.
