### ISSUE TITLE
Cannot upload photos after Mac update

### ISSUE THREAD

**Issue by fishflaovredants** [esteemapp/esteem-surfer#285]
After updating to 2.2.6 I can no longer upload photos.

**Comment by feruzm** [comment]
Thank you for your report. Could you specify what login method you have used? Have you tried to logout, remove and login again to see if it works?

**Comment by fishflaovredants** [comment]
I tried it.   I removed the update and now I can upload photos again.

Il Mer 29 Apr 2020, 14:27 Feruz M <notifications@github.com> ha scritto:

**Comment by feruzm** [comment]
You removed, using 2.2.5? It is always recommended to use latest version. If you could elaborate more on what login method you have used, perhaps we could find the cause of the issue.

**Comment by fishflaovredants** [comment]
Yes 2.2.5.  I'd love to use 2.2.6 if it performed the functions that I
use.  I logged in on the esteem app for mac.

Il Mer 29 Apr 2020, 14:59 Feruz M <notifications@github.com> ha scritto:
