### ISSUE TITLE
@ura-soul report

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#36]
Bugs / Feature Suggestions

Being that this is just version 1 of the app, there are a few bugs and things missing from the functionality that will be quite easy to fix. Here's a few that I have seen:

1. ~~There's currently only a single button in the text editor to insert a single hash symbol for a level 1 heading... It would be much better to have multiple buttons, one for each heading size.~~
2. ~~Keyboard shortcuts for text formatting don't work in the text editor. It would be great to be able to use standard shortcuts such as Ctrl+i to set text to italic.~~
3. ~~The calculation used to convert post payouts to other currencies, such as GBP or USD is incorrectly assuming that the market price of SBDs is 1USD, which is clearly incorrect and so the post payout figures in Surfer are wrong. I spoke with @good-karma about this and pointed him to steem.supply, which has a good explanation of how to correctly convert projected post payout values into real world fiat values.~~
4. ~~There is currently no way to upload images via the interface, I can only add an image that is hosted elsewhere. It would be ideal if Surfer could upload images to the image hosting used by steemit.com.~~
5. ~~Clicking 'save' for a draft more than once, results in new drafts each time. This is not the expected behaviour, as in every other app doing this would result in the saved version of the current draft being updated, not a new draft (copy) being created.~~
6. ~~Tooltips over the shortcuts next to the text in put field would be nice.~~
7. ~~If I upvote posts I can only upvote at 100%, there is no slider for lower percentages.~~
8. ~~If I unvote a post, the value for the post payout and also the number of votes for the post are not updated (reduced).~~
9. There is an option to view 'Leaderboard' activity which shows users with a number / score next to them, but I have no clue what this refers to. More descriptive information is needed there.
10. ~~I have not yet seen any kind of realtime notifications in the app, such as for replies or upvotes - that would be great.~~
11. ~~The 'Discover' page is a bit odd in that it includes people I am already following so I can't really 'discover' them. Also, when I click on the user images on that page, nothing happens, even though the cursor turns to a hand.~~
12. ~~If I search for my username in the search tool, I see myself in the list of profiles at the top, but the actual list of posts that appears underneath contains nothing by me or that mentions me.. soo.. it's not very useful!~~
13. ~~Adding a new line in the text editor does not always result in a new line being visible in the preview (and presumably in the finished post. I have had to add BR HTML elements in a few places to get the spacing right. Steemit.com does not have this issue.~~
14. ~~It would be great to be able to see the global URL for the post once it has bee posted to the blockchain. If I want to link people to my post in comments, I'm not sure how to get it's address to point them to it).~~
15. ~~The scheduled post I made did not actually post and I had no notification that it didn't post. When I converted it back to a draft, the list of tags had been changed so that commas were in the tag list instead of spaces.~~

**Comment by talhasch** [comment]
1. Heading variants added with sub menu.
<img width="439" alt="ekran resmi 2018-05-23 17 12 14" src="https://user-images.githubusercontent.com/1177676/40429914-768c8bf4-5eac-11e8-888e-e49e764edaa3.png">

2. Keyboard shortcuts added for bold (ctrl+b) and italic (ctrl+i)

4. Image options added with sub menu.
<img width="269" alt="ekran resmi 2018-05-23 17 13 13" src="https://user-images.githubusercontent.com/1177676/40429980-a3d9f88a-5eac-11e8-8076-af45f6e052e2.png">

6. Tooltips added to editor buttons.

**Comment by talhasch** [comment]
14. scheduling bug fixed

**Comment by talhasch** [comment]
14- Floating post menu allows users to see global post urls both for steemit and busy

**Comment by talhasch** [comment]
13- surfer and steemit editor behavior for new lines are same:

![gif1](https://user-images.githubusercontent.com/1177676/40774835-5184d68a-64cf-11e8-98a7-5a2b0a51d665.gif)

![gif2](https://user-images.githubusercontent.com/1177676/40774843-551d1dd4-64cf-11e8-908f-b7effbd45ebf.gif)

**Comment by talhasch** [comment]
3- fixed https://github.com/esteemapp/esteem-surfer/commit/bab659adcfa80e17c1c5e81accbf9d4f3d79ac55

**Comment by talhasch** [comment]
12- Search results will be automatically improved when we created our own search indexes and endpoints.

**Comment by talhasch** [comment]
7-8- we have made lot of improvements for voting.

**Comment by talhasch** [comment]
10- will be implemented with #18

**Comment by talhasch** [comment]
5- will be fixed with #68

**Comment by talhasch** [comment]
@feruzm all completed but 9
