### ISSUE TITLE
Damaged View using Notebook

### ISSUE THREAD

**Issue by zikraa** [esteemapp/esteem-surfer#37]
This is the screenshot I took from the person who felt it

![bug](https://user-images.githubusercontent.com/33521049/40280314-5cd2f460-5c7b-11e8-83a0-e1a85e70a271.png)
![bug1](https://user-images.githubusercontent.com/33521049/40280315-5d0560f8-5c7b-11e8-8f2d-7312a92933b4.png)
![bug2](https://user-images.githubusercontent.com/33521049/40280316-5d396b0a-5c7b-11e8-83d8-2ba53977e175.png)

**Comment by horpeyloaded** [comment]
please can you make the issue more detailed

**Comment by feruzm** [comment]
@zikraa what is damaged, if you could elaborate, it would be helpful

**Comment by talhasch** [comment]
Minimum window size reduced to 1000x600px from 1200x700px to display properly on smaller screens. https://github.com/esteemapp/esteem-surfer/commit/25dd4b0f0ce99171dcebd3fcc42a38889b8a305a
