### ISSUE TITLE
Issues and Suggesstions 

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-surfer#38]
### Suggestions
1. ~~implement "favourite" feature like the one of the mobile App~~

***
2. ~~Word counter feature when typing articles~~

***
3. Article details for readers (total words, mins to read) 

***
4. Add a voice reader

***
5. Display SP instead of Vest in wallet details 

***
6. spell checker

***
7. ~~user should see link when they hover over it before clicking to avoid dangerous/misleading links~~

***
8. ~~Insert images by dragging & dropping, pasting from the clipboard, or by selecting them~~

***
9. ~~Looks nice! Unfortunately it has no settings to change the font size or to [Ctrl]+[+] to zoom in like a browser. My eyesight is poor so I can not use it without changing display settings to a lower resolution.~ 

***
10. ~~**user modemser62:**
On the settings, everything is too small you may use the entire vertical space on the screen to expand the feed and new posts should be in the middle and have attached hot trending etc
To expand the app to widescreen optimization for displaying the content.
to try to help videos to pop up like on busy.org or better.
music is nonexistent probably when you get a search to be able to tick a box for what you need video or music and to make this also an option in the client search for music search for video and explore trending hot etc~~ 

***
11. ~~flag 🚩 in comments~

***
12. ~~Potential payout for both posts and comments should be implemented `steem.supply has this, suggested by @horpey`~~

***
13. ~~regarding the delegation on wallet, many people find it hard to delegate and to check their delegation details, I suggest  there should be a layer where user can easily delegate and check their delegation details~~
`suggested by @horpey`

***
14. ~~ability to block spammer users posting links;
**filter some users comment**: implement an option for users to filter out specific user comment. there are some spammers who like to spam comments with links… , if they are filtered/ blacklisted out, users who filtered them won't see their useless comments.~~
`suggested by @horpey`

***
15. ~~`rapheal on discord: community manager of warex` suggested:
Can we have dlive, dtube, dsound and a web browser all integrated into the esteem platform?
**To my on view:** Since eSteem is an hybrid App/Software(Browser and System or Mobile API), I suggest, if we can integrate browser so users can navigate to their specific url **or** there should be a panel/page where links of trusted platforms built of Steem (such as dlive, dtube, dsound, dmania) will be listed and if any user click on any of those links, it should take them to the site within eSteem surfer. **With this suggestion, users will get obsessed by using eSteem surfer as there favorite browser**~~

***
### Issues
16. ~~when a link is used as location on profile, the link is not clickable~~

***
17. ~~clicking username from Upvote List(Voters info) does nothing~

***
18. ~~it does not support all fonts
`This desktop version isn't support myanmar font.`~~ 

***
19. ~~reblog icon missing~~

***
20. ~~upvote button not working as it should~

***
21. ~~The UPVOTE function (self-vote) in the Surfer 1.0.0's editor doesn't work. So when I hit the small box the vote is not allocated then.~~

***
22. ~~conversion to local currencies for expected post payouts? I ask because when I compare the figures I see in GBP to what I would expect based on the figures I usually use at steemstats.com - they don't match up😊😊😊.
**I added to this,** regarding the list of currencies, STU should be an option instead of USD (STU should replace USD) because this displays Steem Token Unit instead of the precise value in USD, added USD should show the post payout regarding the present value of steem and sbd for example if a post has 10STU as the post payout, USD should display the value in $, [10STU 75% for author and 25% for curator will give 7.5 for authors and 2.5SP for curators, now 7.5/2=3.75 this will give 3.75 in SBD and 3.75 in SP but SP are rewarded base on value of steem, here let's assume the value of SBD to be 2$ and Steem to be $3. This will be 3.75/3 =1.25 now the user will get 3.75SBD and 1.25SP with the present value in dollar user will get (3.75×2 and 1.25×3 = 11.25$) the curators reward is 2.5SP×3=$7.5. So the value to display in **USD** for a post payout of 10$ will be $18.75 and it will show *author rewards:* 11.25$ and *curators reward:* 7.5$]~

***
23. ~~a user complained that, as soon as he closes eSteem Surfer, it gets uninstalled and he has to re-install to use surfer again `@cambridgeport90 -user on eSteem discord channel`~~

***

**Comment by talhasch** [comment]
1. Favourites already implemented.

<img width="255" alt="1" src="https://user-images.githubusercontent.com/1177676/40430478-e1234ae2-5ead-11e8-9b5f-050c418e6e86.png">
<img width="643" alt="2" src="https://user-images.githubusercontent.com/1177676/40430481-e39f118e-5ead-11e8-8ac3-aee478725ef5.png">

8. All of these upload options are already exists:  drag & drop, paste from the clipboard an selecting via file input.

9. Zooming enabled. https://github.com/eSteemApp/esteem-surfer/commit/5c86d5dc185cf6ec4e9e859bcf3d16c00ceaf7e3

**Comment by talhasch** [comment]
18. Actually Windows 7 issue. Has no support for myanmar font.  It has to be declared myanmar iso code to html which we cant do.

Same issue on busy and steemit: 

<img width="1364" alt="1" src="https://user-images.githubusercontent.com/1177676/40506989-1669f0fa-5fa0-11e8-8de7-f0fbc51fb7b3.png">

<img width="1364" alt="2" src="https://user-images.githubusercontent.com/1177676/40507092-217d1de6-5fa0-11e8-8075-36291a77ce52.png">

**Comment by horpeyloaded** [comment]
## Issues

## Suggestions 
- **Toast Notification** for upvotes, transfer, reblog

**Comment by talhasch** [comment]
11. comment flagging implemented

19. post reblogging implemented

**Comment by horpeyloaded** [comment]
@talhasch @feruzm good work, I commend your efforts

**Comment by talhasch** [comment]
13- delegation implemented. we will implement delegations received soon.

**Comment by talhasch** [comment]
2- word counter added to editor.

![image](https://user-images.githubusercontent.com/1177676/41532180-a9755832-72fe-11e8-8358-46e8bf53c08c.png)

@feruzm new feature

**Comment by talhasch** [comment]
15- NO

**Comment by talhasch** [comment]
14- hiding comments from spammers already implemented.

**Comment by feruzm** [comment]
please create separate issue to track new features and issues, thank you!
