### ISSUE TITLE
Night mode toggle on header

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#40]
Night mode is mostly requested feature after release, let's prioritize this.

**Comment by talhasch** [comment]
Added it to end of user dropdown navbar. 

<img width="674" alt="ekran resmi 2018-05-22 14 51 08" src="https://user-images.githubusercontent.com/1177676/40360708-a9ccdd8a-5dcf-11e8-9bae-09e8c1451099.png">

What do you think?

or i can move it to before activities icon with this icon: https://fontawesome.com/v4.7.0/icon/eye/

**Comment by feruzm** [comment]
@talhasch let's use https://fontawesome.com/v4.7.0/icon/lightbulb-o/ or https://fontawesome.com/v4.7.0/icon/moon-o/ and move for quick access

and also please make those icons slightly smaller

**Comment by talhasch** [comment]
Night mode button moved to top navbar https://github.com/eSteemApp/esteem-surfer/commit/9b741feef7944eb7c4e9eb06cd5f140dd118554f
