### ISSUE TITLE
Opening Draft tag issue

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#42]
![](https://cdn.discordapp.com/attachments/426658244556226571/448027063383883776/unknown.png)

Tags are separated by space but on Draft backend they are saved with `,`, when opening draft to editor please make sure to remove `,` and replace with ` ` space

**Comment by talhasch** [comment]
Added some code to fix it. Can you please check with draft that includes comma?

**Comment by feruzm** [comment]
fixed
