### ISSUE TITLE
Comment dedicated page

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#43]
Opening whole post when opening comment is working really good because you can see whole thread and scrolling to specific comment section, but let's add comment dedicated page as well:

Example: https://steemit.com/esteem/@v4vapid/re-good-karma-re-ura-soul-2018520t133556434z-20180521t034632116z

dedicated comment page would only open if `comment.depth > 1` like in above example. But If `comment.depth == 1` we can leave as it is now, open whole thread and scroll to comment...

**Comment by talhasch** [comment]
Implemented 

![output](https://user-images.githubusercontent.com/1177676/40742051-f27af26a-6455-11e8-888d-a264623a5e4c.gif)
