### ISSUE TITLE
All Modal window sizes

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#45]
Please make all Modals screens at least 80% width and 70% height

**Comment by talhasch** [comment]
Making all modals 80% width will not have nice looking.

Check images below: 

![image](https://user-images.githubusercontent.com/1177676/40359504-b357f186-5dcb-11e8-9196-79122b391cd7.png)

![image](https://user-images.githubusercontent.com/1177676/40359527-c48ed1fe-5dcb-11e8-9d95-e340a24394dd.png)

![image](https://user-images.githubusercontent.com/1177676/40359529-c76e494a-5dcb-11e8-895b-c13a6ae24bff.png)

As you can see there are a lot of unused space.

I think we should enlarge modals only we need to. For now: follower and following list modals.

**Comment by feruzm** [comment]
@talhasch makes sense, looks like there are some exceptions...
