### ISSUE TITLE
Reading experience

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#46]
![image](https://user-images.githubusercontent.com/3015990/40305955-72d7ae24-5d05-11e8-8a1f-2b042f10dec7.png)

Safari has reading mode for most websites, wikipedia as an example. Let's discuss if it makes sense to have similar styling, although medium.com, steemit.com and Surfer is quite good without any styling as well

**Comment by fildunsky** [comment]
Maybe it should be just a high contrast theme in future with an option to switch it on/off in settings?

**Comment by talhasch** [comment]
Implemented https://github.com/esteemapp/esteem-surfer/commit/5b641091899b56962c3b850739592f1041931741 @feruzm @fildunsky

**Comment by feruzm** [comment]
there is strange flicker when transition happens, is there way to smooth transition? @talhasch
