### ISSUE TITLE
Sharing, Resteem button location

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#47]
What do you think on left side vertical floating buttons?

![image](https://user-images.githubusercontent.com/3015990/40306123-13ca3c16-5d06-11e8-9bdf-f275d4bb8f74.png)

**Comment by horpeyloaded** [comment]
nice suggestion I love the left bar

**Comment by talhasch** [comment]
Final implementation:

<img width="1312" alt="final" src="https://user-images.githubusercontent.com/1177676/40577537-fe993686-610f-11e8-9c14-35b523305a1e.png">

**Comment by fildunsky** [comment]
Looking awesome! How do you do such a beautiful screenshots with the shadow by the way?

**Comment by talhasch** [comment]
it is an osx feature. command + shift + 4 + space then click the window you want to take screenshot.
