### ISSUE TITLE
Relevant posts

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#48]
Between post body and Comments section, add Relevant posts section where 3-5 posts are featured which has similar tags and content that might interest readers.

**Comment by fildunsky** [comment]
It's great idea and should be implemented but maybe with an option to switch it off in settings?

**Comment by feruzm** [comment]
closing this @talhasch, but Settings page should have option to select by Author and/or by Tags maybe with next release.

**Comment by fildunsky** [comment]
Quick suggestion/request to exclude current user posts from this. I use this relevant posts option often and it's very handy for me to find new interesting authours (especially for arts/designs) but sometimes I see my own posts in this row. I am not sure they have to be there...

**Comment by talhasch** [comment]
active user's posts excluded from the similar post list @fildunsky

**Comment by fildunsky** [comment]
Cool! Thanks a lot!
