### ISSUE TITLE
External links with icon

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#5]
Having similar icon if content has external link would be perfect to give user a notice before attempting to open link

<img width="301" alt="screen shot 2018-03-11 at 4 08 01 pm" src="https://user-images.githubusercontent.com/3015990/37254434-7b4f44f0-2546-11e8-8e09-4ef9742015b6.png">

**Comment by talhasch** [comment]
implemented https://github.com/eSteemApp/esteem-surfer/commit/17ff3f771ef918b0752d8c0c65443b29c8c1a4c7
