### ISSUE TITLE
Graphic Resizing & Table Coding Issues

### ISSUE THREAD

**Issue by LilahLee** [esteemapp/esteem-surfer#52]
## Hello...I am wondering why my horizontal heart dividers don't resize well. This is what they normally look like through the steemit website...

![s01](https://user-images.githubusercontent.com/39504642/40335122-eec4cdf8-5d16-11e8-968a-7cb66b1478b1.png)

## And this is how the surfer ends up stretching them!

![s02](https://user-images.githubusercontent.com/39504642/40335190-462f3a24-5d17-11e8-8560-2f69656e31ed.png)

## Also...I have used some basic table coding which appears fine on the website...

![s03](https://user-images.githubusercontent.com/39504642/40335250-919233c2-5d17-11e8-9064-e7f56765b907.png)

## But the surfer ends up stretching these images too!

![s04](https://user-images.githubusercontent.com/39504642/40335285-b7511c54-5d17-11e8-965a-ed23c94b619c.png)

## The full width banners and my cover image resize perfectly okay on both the website and the surfer. Here is the link that I used for the screenshots so that you can see what I mean... 

https://steemit.com/creativecommons/@creativesoul/creative-commons-coloring-page-collection-kaleidoscope-series-03

**Comment by horpeyloaded** [comment]
The heading tags including `<h3></h3>` works fine
![2018-05-24 22_44_10-esteem surfer](https://user-images.githubusercontent.com/34909705/40515301-2ce99566-5fa4-11e8-9fe3-180a1b451c1d.png)

**Comment by talhasch** [comment]
@feruzm just found problem. fixed https://github.com/esteemapp/esteem-surfer/commit/4ac215228f7fd90e082154b83503bd4c33e08b7a

![1](https://user-images.githubusercontent.com/1177676/40739768-ba0503e0-644f-11e8-992b-d65db7383c89.png)

![2](https://user-images.githubusercontent.com/1177676/40739774-beecbb78-644f-11e8-88b1-302fb65cdbaf.png)
