### ISSUE TITLE
Adapt BadActors list

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#53]
There is badactors list which is used for transfers, these account's intent is to take advantage of mistype errors. Please adapt this so that whenever user enters or mistypes and gets these usernames, warn them about account being `Bad Actor / mistyped account name detected?!`

https://github.com/steemit/condenser/blob/master/src/app/utils/BadActorList.js

**Comment by talhasch** [comment]
Adapted https://github.com/esteemapp/esteem-surfer/commit/57ab6eb532fcc528e15ab75c40ee5b72d8806ca9
