### ISSUE TITLE
Can't update a post I already voted on - RPCError: Assert Exception:_c. abs_rshares == 0

### ISSUE THREAD

**Issue by royachiron** [esteemapp/esteem-surfer#62]
See the gif. I edit a post I've voted on, and when I try to update it, it won't let me, giving me this error:
![image](https://user-images.githubusercontent.com/23020420/40815748-5123f176-6551-11e8-9bd3-3a135edd81a9.png)
See GIF
![21](https://user-images.githubusercontent.com/23020420/40815753-57b53f90-6551-11e8-8b87-b6607171e43f.gif)
Editing posts or comments you upvoted is totally doable on steemit (and I believe other steem front ends)

**Comment by fildunsky** [comment]
Can not confirm that. Somehow for me post editing always works fine even after self-upvote.
