### ISSUE TITLE
esurfer - Auto refreshing FEED page on both tabs

### ISSUE THREAD

**Issue by steemflow** [esteemapp/esteem-surfer#63]
The FEED tab option on the @esteem esurfer page gives the feeding post from your following list.

@esteem surfer gives you 2 tabs for viewing the FEED page. The user can scroll on the FEED page either through the top Feed button on the esurfer page, 

![image](https://user-images.githubusercontent.com/36257185/40834071-650fae94-65ad-11e8-8ec9-80279ae737ec.png)

Or through the Feed option from Profile page., with multiple tabs like blogs-feed-comments-replies etc.

![image](https://user-images.githubusercontent.com/36257185/40834080-73ef8a10-65ad-11e8-8016-86436ca7fd6a.png)

It has been noticed that, even after refreshing either of the page to view the latest posts, the other FEED page is not getting automatically refreshed. We need to refresh the both the FEED one by one to view .

As FEED page is common in both the tabs. Both will need to get refreshed simultaneously, after refreshing either of the page. 

I have the video captured for the same. Hopefuly, I manage to explain the issue, that @esteem esurfer is facing.

Thanks
@steemflow

**Comment by talhasch** [comment]
Thanks for you feedback @steemflow 

Technically, we have a navigation manager and it caches every page separately. This is why those 2 sections are rendering differently.

But yeah, you are right. synchronizing those 2 sections is better behaviour for user experience.
 
Will be implemented soon...

**Comment by steemflow** [comment]
Thanks talhasch :) Good to have my input considered.
