### ISSUE TITLE
Bug: Decline Payout post rewards setting is not working on eSteem surfer

### ISSUE THREAD

**Issue by sourovafrin** [esteemapp/esteem-surfer#64]
#### Expected behavior

We can generally post from eSteem surfer and at the time of posting we can set post rewards to-

- Default 50%/50%

- Power Up 100%

- Decline Payout

#### Actual behavior

I tried to write a post setting the post rewards on **Decline Payout**. But when i checked my post i saw that it was showing pending post rewards.

#### How to reproduce

- [Click here](https://github.com/eSteemApp/esteem-surfer/releases/tag/1.0.1) and download the windows version of esteem surfer.

- Now unzip the file and install the esteem surfer software.

- After being installed, open the software and login to esteem surfer by your account's posting key.

- Now write a post, and set the post **Rewards** to **Decline Payout** and click on post it.

- But you will see that the post it show you your pending rewards

* Software version: eSteem Surfer 1.0.1

* Operating system: Windows 8.1

#### Recording Of The Bug
https://youtu.be/xnTczSynXlQ

**Comment by fildunsky** [comment]
Checked and can confirm that bug. Decline payout option is not working. Looks like the post is created with 50/50 option instead.
