### ISSUE TITLE
Suggestions to Add Synchronize Tab in Editor 

### ISSUE THREAD

**Issue by rosatravels** [esteemapp/esteem-surfer#65]
I want to propose an EXTRA TAB where it SYNCHRONIZES both of these scrolling. In this way when we scroll on the Editing page we can actually see what it looks like on the right side Preview panel or vice versa. And when we see that something does not look right on the preview panel, we can right away make the changes on the Editing panel in the right location without the need to scroll from the Editing panel.

![image](https://user-images.githubusercontent.com/33372725/40851117-f1cc350a-65f8-11e8-8e26-34bfc2a5ec39.png)

- Add the new Tab "S" - Synchronize on the left side of the Editor

- When this tab is activated, both the scrolling for Editing side and the Preview side will coincide together

- I boxed in the 2 scrolling in red - can you see that the scrolling of the Editing panel and the scrolling on the Preview Panel coincide together. They are now at the same place.

- This means that what you see on the Editing panel is exactly in the same location of the Preview panel on the right.

Can you see how awesome this will be for Users posting via Esteem Surfer?

This will make this the #1 Posting editor for Steemit.

The benefits of having the Synchronize Tab on the Editor:

- Users can activate the Synchronize tab for easy proofreading!

- When users proofread their posts which we often do before posting, we can scroll down the editing to look at the preview alongside at the same location. Right now you need to do it manually by scrolling both panels.

- And when we see that in the preview, there is a mistake, we can right away know where to make the 'editing correction' on the left panel because the synchronized tab will show the exact location for both windows (editing and preview)

This saves a lot of time in proofreading where we can just make correction right away whenever we spot a mistake.

**Comment by talhasch** [comment]
Thanks for your suggestion @rosatravels 

Editor->output synchronizing can be great feature for composing posts.

Added it to our feature list.

**Comment by talhasch** [comment]
Editor synchronization implemented with v2 🎉
