### ISSUE TITLE
Some Problems and Sugestion For Esteem Surfer

### ISSUE THREAD

**Issue by ijoellsm** [esteemapp/esteem-surfer#66]
<div class="text-justify">I am one a user of esteem, in my post, I would like to convey some of the obstacles (problems) that I found in using esteem surfer during I using surfer esteem recent. 

<strong>Issues I Found in Esteem Surfer version 1.0.1</strong>

<strong>1) Must Perform Installation Process Everytime Login</strong>

<div class="text-justify">As I know, usually every application that has been installed in laptop or computer, enough once doing a process of installation. After that, we can run the application by clicking on the icon of the app that is on the desktop. The problem can be seen in the following pictures and videos

<center>https://cdn.steemitimages.com/DQmc4AYFAxZKSSgKruCjJfwZSooKViC9ENaZN7Duu1vCUjf/.png</center>
***

https://youtu.be/-MKZMYKMuPw

<div class="text-justify">Every time log in esteem surfers always appears like that. This means that the surfer esteem app on my laptop is not permanently installed. I have to do and go through the installation process again every login. 

<strong>2) Cannot Favoriting One User With Using Favorite Menu</strong>

<div class="text-justify">To easily bookmark one of the other users I have idolized so it's easy for me to find it, in this case, I use the favorite menu in the surfer's esteem on my laptop, but the surfer esteem which installed on my laptop as such as there are few constraints so I cannot to favoriting one or more other users I idolized.  Regarding this second issue, you can look at the following video.

https://youtu.be/W3tPHd-_xP8

<strong>3)Fetcherorr Request to https://api.steemit.com</strong>
<div class="text-justify">Whereas esteem surfer or mobile esteem that I use, the setting  is correct in server menu - https://api.steemit.com. For more details can be seen from the following video.</div>

https://youtu.be/7rVbp0BodqE

## <strong>Suggestion</strong>

<div class="text-justify">To the problems or constraints of the esteem surfer, I find this needs a solution to fix bugs from the esteem application. For the first problem, I suggest that the esteem application should be fixed although it is still in beta format, at least it could be like a portable app. That is, just once install direct permanent. For the second login and then no longer need to wait for the application installation process.

For the second and third problems, I hope there is a solution, so all the features available in the esteem can used by all users perfectly.</div>

I think this is the first thing I can say about the esteem issues if I find any obstacles or other problems, I will immediately report to make the esteem more perfect, and become the mainstay application that wished by all steemit users as the priority application.</div>

## Note:
I'm using a Dell Inspiron 11-3162 laptop with a Windows 10 Pro-64 bit as the operation system

## <center><strong>Much Love</strong></center>

<center><strong>Thanks For Your Time</strong></center>
<center><strong>The Best Regards, @ijoel</strong></center>
***
<center><strong><sub> Stop spam, scam, and phishing on my blog</sub></strong></center>

**Comment by feruzm** [comment]
should be fixed by now, please create new issue if you find something is not working. Thank you!
