### ISSUE TITLE
Some pictures fail to display

### ISSUE THREAD

**Issue by AndaBlackWidow** [esteemapp/esteem-surfer#73]
eSteem Surfer v1.0.2 (the same problem happens on Mobile)
example of bad behaviour:
https://steemit.com/pl-fotografia/@photo.ethernity/imp-impro-improwizacja

Displays properly in regular browser, but Surfer fails to display some pictures. All pictures are jpg, all are hosted on steemitimages.com, all are similar sizes so the problem is elsewhere.
The most likely source of trouble is URL encoding - all links to images that don't show up end with .jpg%3C/p
F.e.:
Shows ok - https://steemitimages.com/0x0/https://cdn.steemitimages.com/DQma1bUAh4Arc8qKXJo7E1fke3k8WBe2qzHsJFvCSDDMqfs/Bez%20nazwy-1.jpg
Does not show - https://steemitimages.com/0x0/https://cdn.steemitimages.com/DQmeepqT5TYgPiSHuqJG4PUaDpqCmSwECziQEBBNUwdpQxZ/5.jpg%3C/p

**Comment by talhasch** [comment]
@AndaBlackWidow we are aware of this issue. will be fixed in next release. thanks.

**Comment by feruzm** [comment]
@AndaBlackWidow thanks for getting back!
