### ISSUE TITLE
Background color for selected comment makes it unreadable in Night Mode

### ISSUE THREAD

**Issue by AndaBlackWidow** [esteemapp/esteem-surfer#75]
eSteem Surfer v1.0.2
steps to reproduce:
Go to Profile/Comments or Profile/Replies, click on any comment  - it will be distinguished from other comments with yellow background; turn on Night Mode - the text color changes to pale violet/blue but background color stays unchanged which means the contrast is very weak and text is unreadable.

**Comment by feruzm** [comment]
Good find, we will fix it with this week's release! @talhasch

**Comment by AndaBlackWidow** [comment]
Seems to be fixed in Surfer 1.0.3

To be honest I didn't notice in earlier version, so maybe it was always like this (and then it would not be a bug but enhancement worthy of separate issue) but only the top comment is ever distinguished with special colors (by top I mean comment to main post as opposed to comment on other comment). If you choose comment/reply that is deeper and then go to full context you will not have that visual aid - seems weird since that's where the feature would be even more useful (also going to full context should move the view to the comment instead of top of main post - scrolling to main post is always easy, scrolling down/through pages and finding relevant branch of discussion... not so much).

**Comment by feruzm** [comment]
Would you elaborate on your thoughts and perhaps suggest how you see comments could be improved more... on separate new issue?! Thanks
