### ISSUE TITLE
Voters info popover

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#78]
Add popover to vote numbers that shows top 10 voter when mouse is hovering over it and add `more...` text that will open current Voters info page.

Example: 

![image](https://user-images.githubusercontent.com/3015990/41156638-777c947e-6b2b-11e8-85e8-59deeec64863.png)

**Comment by talhasch** [comment]
Implemented @feruzm 

![image](https://user-images.githubusercontent.com/1177676/41820031-c0e2eb22-77d3-11e8-8037-3ddfca5e1af7.png)

![image](https://user-images.githubusercontent.com/1177676/41820037-dcb805c6-77d3-11e8-9860-afa32db92397.png)
