### ISSUE TITLE
Unable to navigate into Author account from Post Comment section in @esteem esurfer

### ISSUE THREAD

**Issue by steemflow** [esteemapp/esteem-surfer#79]
While viewing any post in the FEED section on @esteem esurfer, we can directly navigate to the author account, by clicking on the "Author Name"

For example, the below feed is appearing on my feed page, 
![image](https://user-images.githubusercontent.com/36257185/41168383-6af65aea-6b63-11e8-9735-9970da2acc93.png)

If we click on the author name, which happen to be @inthenow, It will directly navigate me to the user account. Refer below screenshot.

![image](https://user-images.githubusercontent.com/36257185/41168466-af77da0e-6b63-11e8-9e59-4e70f4a0f935.png)

However, if we click any author name from the **Comment** section of any post on @esteem esurfer, it only displaying me the name and not  navigating to the user account.

Refer below screenshot:  tried to open the user account, from the comment section of one of the post , instead of navigating me to the user account which happens to be @oldtimer, it flashes me account details of "Follow" or "Unfollow"

![image](https://user-images.githubusercontent.com/36257185/41168717-65f22848-6b64-11e8-9920-852673034a51.png)
.
In case , i tried to open such user account from any other Steem app, it will directly navigate me to the Author account from the Comment section. Hope I manage to explain the issue properly.

The issue is currently with the "Commentor" in the comment section.

Thanks @steemflow

**Comment by fildunsky** [comment]
Looks like this is not a bug but a feature so you can see user info in the tooltip. Then you can click on the @username inside that tooltip and you will be able to open user profile.

**Comment by talhasch** [comment]
@steemflow you can click user name, screen name or profile picture to navigate to author page.
