### ISSUE TITLE
Minor problem with night mode+read mode+max window

### ISSUE THREAD

**Issue by AndaBlackWidow** [esteemapp/esteem-surfer#80]
eSteem Surfer 1.0.3
Steps to reproduce: turn on night mode, open post, turn on new read mode (if Surfer window was maximized it will narrow down to width of post text - is that intentional?), maximize Surfer window - on both sides of the text at the bottom white stripes will appear, scroll down to see them better.

**Comment by talhasch** [comment]
@AndaBlackWidow yes that is intentional. @feruzm what do you think about making window maximized on reading mode?

**Comment by feruzm** [comment]
@talhasch we can max window size on reader view, without OS distractions as well :)

**Comment by AndaBlackWidow** [comment]
I'd prefer if window stayed maximized in read mode if it was maximized before. If it wasn't maxed at the start both keeping the size and resizing (narrowing) to text width is ok imho. However this issue is about visual artifact:
![issue80](https://user-images.githubusercontent.com/30322003/41566964-413f58c0-735e-11e8-9b60-b5cbfbdc30d0.jpg)
I'm using it in 4k resolution - maybe that is the source of a problem? I've noticed that similar artifacts sometimes show as a stripe at the bottom of window if article is short (the one in the screenshot is this: https://steemit.com/economics/@dollarvigilante/domino-s-pizza-answers-statists-who-ask-who-will-build-muh-roads )

**Comment by talhasch** [comment]
fixed. #114
