### ISSUE TITLE
Youtube hyperlink display issue

### ISSUE THREAD

**Issue by jznsamuel** [esteemapp/esteem-surfer#81]
In my blog, when I mention a youtube hyperlink, although it shows as a link on busy/steemit, the full video is rendered in eSteem surfer.

From steemit:
![image](https://user-images.githubusercontent.com/34867122/41203274-559fb908-6cf2-11e8-8d0d-d87f9f9ae005.png)

From eSteem surfer:
![image](https://user-images.githubusercontent.com/34867122/41203302-a2f7b674-6cf2-11e8-911b-e4e683560b1b.png)

**Comment by talhasch** [comment]
fixed @jznsamuel
