### ISSUE TITLE
Link to profile not displaying for all references

### ISSUE THREAD

**Issue by jznsamuel** [esteemapp/esteem-surfer#82]
When multiple account names are mentioned in my blog, I can see all the hyperlinks in steemit/busy, while only partial accounts seems to get referenced/displayed in eSteem surfer.

From steemit:
![image](https://user-images.githubusercontent.com/34867122/41203356-47e9fe58-6cf3-11e8-9ec7-2e36f365c92a.png)

From eSteem surfer:
![image](https://user-images.githubusercontent.com/34867122/41203363-618d56b6-6cf3-11e8-90e0-343563bde49c.png)

**Comment by talhasch** [comment]
nice catching @jznsamuel 
fixed.

![image](https://user-images.githubusercontent.com/1177676/41511637-b45fd64e-7283-11e8-8dea-4bc1e8873995.png)
