### ISSUE TITLE
No Quit option from menu

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#85]
Windows and Mac versions have standard application menu but there are no File -> Quit option and it's impossible to quit app using hotkeys like cmd+q this way

**Comment by talhasch** [comment]
quit menu item added. 

![image](https://user-images.githubusercontent.com/1177676/41781440-2fdceebe-7640-11e8-9dde-18dafd0fb2d9.png)

![image](https://user-images.githubusercontent.com/1177676/41781442-32447fe6-7640-11e8-96f6-66db3b26d11e.png)

@fildunsky 
@feruzm
