### ISSUE TITLE
are the images posted in steepshot not displayed in the gallery?

### ISSUE THREAD

**Issue by muhammadarif1** [esteemapp/esteem-surfer#86]

**Comment by talhasch** [comment]
@muhammadarif1 no. we have no integration plan for steepshot images with gallery for now. what do you think @feruzm

**Comment by feruzm** [comment]
@talhasch steepshot has their internal gallery and we have our own, just like steemit has their own. For now, there is no way or plans to integrate 3rd party gallery.
