### ISSUE TITLE
[Bug] Markdown Renderer Problem

### ISSUE THREAD

**Issue by josephace135** [esteemapp/esteem-surfer#88]
Expected behavior
The content of a certain Steemit post should appear the same regardless if it is opened or read either in mobile browsers, web browsers, or any Steem-based applications like eSteem Surfer, which is a desktop client for Steemit.

Actual behavior
#### Actual behavior
The markdown renderer in eSteem Surfer wasn't able to correctly display the texts that is supposed to be a snippet of a code. Such as in this [development for Knacksteem post](https://steemit.com/utopian-io/@jaysermendez/knacksteem-api-more-features-added). For code snippets having `@` it is being displayed in eSteem Surfer as a Steemit user/account.  Additionally, for this [tutorial post](https://steemit.com/utopian-io/@chri5h/creating-dynamic-cards-using-angular-js), the code snippets are missing and broken.

Screenshots of the Bug
- Screenshots showing the comparison on what the content looks like using Google Chrome and eSteem Surfer this one is a [Development Update for Knacksteem API](https://steemit.com/utopian-io/@jaysermendez/knacksteem-api-more-features-added)
   - Google Chrome
![knacksteem chrome](https://user-images.githubusercontent.com/35374763/41818220-c39ca3c2-77dc-11e8-898c-99821490b962.png)
   - eSteem Surfer
![knacksteem esteem surfer](https://user-images.githubusercontent.com/35374763/41818226-d8f211ee-77dc-11e8-8e7a-49c657f3cd78.png)

In the comparison show, the code snippet appear wasn't shown properly and is broken.
___

- Screenshots showing the comparison on what the content looks like using Google Chrome and eSteem Surfer this one is a [Tutorials Contribution](https://steemit.com/utopian-io/@chri5h/creating-dynamic-cards-using-angular-js)
   - Google Chrome
![tutorial chrome](https://user-images.githubusercontent.com/35374763/41818244-0b5130c0-77dd-11e8-8862-a9dc8571875b.png)

   - eSteem Surfer
![tutorial esteem surfer](https://user-images.githubusercontent.com/35374763/41818246-10e6c860-77dd-11e8-998f-b72ac7e00401.png)

In this tutorials contribution, the code snippet belongs to "**Step 2: Starting out template**", the code snippet for "**index.html**" is not shown.

**Comment by talhasch** [comment]
Thanks for reporting @josephace135 

fixed.

**Comment by josephace135** [comment]
That was fast! By the way, you're welcome @talhasch :).
