### ISSUE TITLE
[1.0.5] - Navigation corrupt following logging out and creating post  

### ISSUE THREAD

**Issue by tobias-g1** [esteemapp/esteem-surfer#89]
#### Expected behavior
The top navigation options should always be viewable and clickable in both a logged in and logged out state. The following image shows the expected look and feel:

![image.png](https://ipfs.busy.org/ipfs/QmNMuaHHiAkNm375exjRUL3p3qyTFBvfbpQXUWzWTsJ52C)

#### Actual behaviour

After logging out and creating a new post, the navigation is incorrect as is corrupt. The following shows what it looks like after logging out and clicking on create a post. 

![image.png](https://ipfs.busy.org/ipfs/Qmb6qwsc1ccQF6j8BvXSKbbNf9eAziUu7TfGz8JUvXRrZ3)

Note: This only seems to occur first time after logging out and creating a new post. 

#### How to reproduce

  1. In a logged in state, click on the eSteem logo to ensure you're feed.
  2. Click on your profile image in the top right to show additional menu options. 
  3. Click "Login as"
  4. A pop up will be shown which allows you to log in as a new user, you will see your current login shown within this list, click on the log out button shown in the same container as your account name. 
  5. Once pressed, click on the pop underlay to dismiss the "login as" pop up. 
  6. Once back on the feed, click on the pencil icon located in the top right to create a new post. 
  7. The issue can be seen with the navigation options shown on the left of the navigation bar. 

#### Recording of issue

The following video shows the issue in more detail:

https://www.youtube.com/embed/YSdwmvcStO0

#### Environment

- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version of Testing: Version:  1.0.5

**Comment by talhasch** [comment]
Thanks for reporting @tobias-g1 

Fixed.
