### ISSUE TITLE
[Bug] - When clicking links that are from busy.org, the user gets directed to the Feed

### ISSUE THREAD

**Issue by josephace135** [esteemapp/esteem-surfer#91]
#### Expected behavior
In reading posts/blogs/comments  in eSteem Surfer wherein the content of that certain posts/blogs has **Busy** links, when clicking for those links; those links should be opened within the eSteem Surfer or the least should be open in a web browser, say Google Chrome or any other web browser.
#### Actual behavior
I detected the bug when I read the review comment of @tobias-g in my [bug-hunting contribution for eSteem mobile application](https://steemit.com/utopian-io/@josephace135/bug-in-esteem-mobile-app-ios-version-1-6-0-stuck-in-the-text-editor-after-commenting), and since it was provided with links I clicked this [link](https://busy.org/@rosatravels/bug-in-esteem-app-replying-comments-failed-to-post-and-had-to-reinstall), after clicking, it gets directed to the **Feed**. 

#### Recording Of The Bug

___
### Detection at Version 1.0.5

- First way (*Clicking a busy link from the content on a certain post/comment*)

<center>GIF/Screen Recording</center>

![detection of bug busy links in esteem surfer when clicked redirects to the feed](https://user-images.githubusercontent.com/35374763/41863835-8f5470b4-78da-11e8-99af-de8f7f1b8478.gif)

- Second way (*Replying to a certain post, wherein link from busy is placed in the content of the reply and clicking the link form busy*)

Since there are two GIFs/screen recordings for this way of replicating the bug; the first GIF/screen recording, the Steemit link didn’t work and upon doing a counter-checking, the Steemit link in the second GIF/screen recording when clicked is being displayed in eSteem Surfer, thereby making the bug only affecting the links from **busy.org**.

<center>First GIF/Screen Recording</center>

![replication of the bug](https://user-images.githubusercontent.com/35374763/41864278-f7f7adce-78db-11e8-976d-f22e4622b7b1.gif)

<center>Second GIF/Screen Recording</center>

![replication of the bug version 2](https://user-images.githubusercontent.com/35374763/41864464-b2916238-78dc-11e8-9266-522e07a22c8a.gif)

____
### Replication at Version 1.0.6

![bug at version 1 0 6](https://user-images.githubusercontent.com/35374763/42010326-b502062c-7ac0-11e8-9003-209a9d8fc37f.gif)

**Comment by feruzm** [comment]
thanks for reporting, @talhasch busy link parsing might have some issues, please check.

**Comment by talhasch** [comment]
this problem fixed with ver 2. closing.
