### ISSUE TITLE
Post covers for drafts and schedules

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#92]
It would be super handy if drafts list and schedules list would look similar to the feed page having the posts image cover previews. So you could check how it will look in the feed before posting and if you have multiple drafts it would be easier and faster to recognize them in the list.

**Comment by talhasch** [comment]
![image](https://user-images.githubusercontent.com/1177676/42630272-dbb60c18-85de-11e8-86f3-8411bd1b58b6.png)
@fildunsky ?

**Comment by fildunsky** [comment]
Awesome! Love it!

**Comment by fildunsky** [comment]
@talhasch could you please make draft header, text preview and post cover image clickable to edit the draft? I see there is edit button already and it's great but first I've tried to click on that parts of draft without success :)
