### ISSUE TITLE
Option to disable PIN at startup

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#93]
Can we add an option to disable PIN check at Surfer startup? Maybe in settings. Maybe we could ask that pin only once the first important/valuable action should be done? For example I open the app without entering pin and this allows me to browse the feed but when I am trying to upvote someone for the first time after startup I am asked for the PIN once and then I can do it...

**Comment by fildunsky** [comment]
Or at least an option in settings
- [x] Remember PIN

**Comment by feruzm** [comment]
There is security risk involved in this, but I think it can have `save for 1 hour or so` type of setting until next restart of app.

**Comment by talhasch** [comment]
i agree it is a little bit boring to enter pin code often.
but it is important protection for user keys against potential security problems. 
it can save lives. we should not disable it.

**Comment by fildunsky** [comment]
Maybe we can move pin request to wallet page then?

**Comment by talhasch** [comment]
Because of we encrypt all user keys, we need it everywhere of app.

**Comment by talhasch** [comment]
From security angle verifying user every time is important. Closing this one.
