### ISSUE TITLE
 images saved from token exchange tab are'nt saving on esteem surfer gallery or local folder

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem-surfer#94]
#### Expected behavior
The images saved from **token exchange** tab should be saved either on eSteem surfer gallery section or inside a local folder.

#### Actual behavior
No Image was saved both on gallery tab and local folder even after the **save image** tab was clicked.

#### How to reproduce
* Download [eSteem Surfer](https://github.com/eSteemApp/esteem-surfer/releases). Version 1.0.5
* Open eSteem Surfer.
* locate **Token exchange** tab, then click on it .
* locate the camera icon then click on it to snapshot the page.
* Click on **Save Image**
* now , try locating the saved image on the gallery tab or local folders.

* Browser/App version:   and Google Chrome Version 67.0.3396.87
* Operating system: Windows 10 (64-bit)

#### Recording Of The Bug
https://m.youtube.com/watch?v=uwEImt8X2kU

**Comment by realrufans** [comment]
I have just updated my eSteem-surfer to version 1.0.6 and  i was able to reproduce the bug.

https://youtu.be/85qNKGND18k

**Comment by talhasch** [comment]
Thanks for reporting @realrufans 

With new release it will be opened new browser tab.

**Comment by realrufans** [comment]
Okay , but was it really a bug?

**Comment by realrufans** [comment]
I asked that question because of this .
![Screenshot_20180703-183518.png](https://cdn.steemitimages.com/DQmPk41DcPqLQi77EzQSkpPQvfcTwzqJSrVw4fVeDgsHQMJ/Screenshot_20180703-183518.png)

**Comment by feruzm** [comment]
It is not a bug per se but not fully functional/implemented feature yet. We are focusing on more social aspect of Surfer these days, next month we will start to improve Token exchange page

**Comment by realrufans** [comment]
Okay I got it. Thanks
