### ISSUE TITLE
Suggestion to Add 'Toggle Scroll Sync' on Editor

### ISSUE THREAD

**Issue by dodybireuen** [esteemapp/esteem-surfer#95]
When I look at editors in eSteem Surfer, I think we should add the 'Toggle Scroll Sync' feature. The synchronization between the editor and preview columns will provide the user with ease. Maybe this will be similar to the feature available on https://stackedit.io

![toggle scroll sync](https://user-images.githubusercontent.com/33236060/42015481-bb690d24-7ad1-11e8-8751-736a0d036017.gif)

When users do scroll on the column editor then automatically preview columns following it. The 'Toggle Scroll Sync' feature should be enabled and disabled, allowing users to manually enable or disable features.

**Comment by fildunsky** [comment]
Sometimes it may be really useful, thanks for your suggestion!

**Comment by talhasch** [comment]
implemented with v2
