### ISSUE TITLE
Sorting Posts By Payout Displays ''Nothing Here'

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem-surfer#96]
#### Expected behavior
Sorting post using the **Payout** button was expected to display ports posted within 7days according to their total payout (Highest To lowest).

#### Actual behavior
After clicking on the payout button, it displays  a page with **Nothing Here**. 

#### How to reproduce
* Download [eSteem Surfer](https://github.com/eSteemApp/esteem-surfer/releases). Version 1.0.6
* Open eSteem Surfer.
* locate  and click Payout button from the drop down
![Screenshot (7).png](https://cdn.steemitimages.com/DQmSF7KFSPsTeHgFnqccLYazAYK34fpk4MHAquVGYGaUYiR/Screenshot%20(7).png)

* Browser/App version:   and Google Chrome Version 67.0.3396.87
* Operating system: Windows 10 (64-bit)

#### Recording Of The Bug
https://youtu.be/3l5AUUpdmrY

**Comment by feruzm** [comment]
This depends on selected Server from Settings page. 1.0.7 has proper error handling to address this.
