### ISSUE TITLE
Basic markdown code highlighting

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#99]
It would be really helpful to have code highlighted in editor. Especially you could feel it when compiling big complicated posts with lots of images, links and headers. I am barely sinking in the code without highlight. Have to switch to hackmd.io to prepare big post and then copy-paste it into Surfer.

**Comment by fildunsky** [comment]
Crazy idea is to use hackmd.io codebase https://github.com/hackmdio
This is really handy tool for realtime collaborative markdown notes and editor is almost perfect there.

**Comment by feruzm** [comment]
I like that editor as well

**Comment by talhasch** [comment]
At least we need to add highlighting and synchronizing #65 #95

**Comment by talhasch** [comment]
![image](https://user-images.githubusercontent.com/1177676/42660774-d301507c-8634-11e8-857c-a2be156dca10.png)

**Comment by fildunsky** [comment]
Hmm... What's changed here? I don't see difference in current editor and this screenshots yet.

**Comment by talhasch** [comment]
because of github converts gif to image... it highlights selection in editor. uploaded a video to devops discord channel. check it out.

**Comment by talhasch** [comment]
we have markdown code highlighting with version 2 🎉
